package pipelang

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"reflect"
	"strings"
	"testing"

	"dockpipe/src/lib/pipelang/coreeval"
	"dockpipe/src/lib/pipelang/coreir"
	"dockpipe/src/lib/pipelang/gobackend"
)

var checkedInheritanceOperations = []struct{ name, typ, op string }{
	{"add", "int", "+"}, {"subtract", "int", "-"},
	{"multiply", "int", "*"}, {"divide", "float", "/"},
}

func checkedInheritanceSource(typ, op string) string {
	return fmt.Sprintf(`public Class Cursor {
 public Result<%s, ArithmeticError> Continue(Result<%s, ArithmeticError> carrier, %s operand) {
  %s value = propagate(carrier);
  return value %s operand;
 }
}`, typ, typ, typ, typ, op)
}

// Every accepted version is checked independently; identical normalized artifacts
// and generated bytes let one pristine Go execution per operation cover the matrix.
func TestCheckedPropagationInheritanceAdmission(t *testing.T) {
	for _, operation := range checkedInheritanceOperations {
		t.Run(operation.name, func(t *testing.T) {
			var baselineHIR, baselineCore, baselineSemantic, baselineGo []byte
			for version := 56; version <= 93; version++ {
				contract := LanguageContract(fmt.Sprintf("v0.%d.0", version))
				t.Run(string(contract), func(t *testing.T) {
					source := checkedInheritanceSource(operation.typ, operation.op)
					input := semanticTestModuleSet("compiler.cursor", []ModuleInput{testModule("compiler.cursor", "cursor.pipe", source)}, nil)
					input.LanguageContract = contract
					analysis := AnalyzeSemanticModuleSet(input)
					if err := analysis.Error(); err != nil {
						t.Fatal(err)
					}
					projection, err := BuildSemanticProjection(analysis)
					if err != nil {
						t.Fatal(err)
					}
					repeated, err := BuildSemanticProjection(AnalyzeSemanticModuleSet(input))
					if err != nil || !reflect.DeepEqual(projection, repeated) {
						t.Fatal("semantic output changed on repeat")
					}
					typed, err := LowerSemanticMethodToHIR(analysis, semanticMethodNamed(t, analysis, "Continue").Identity)
					if err != nil {
						t.Fatal(err)
					}
					program, err := LowerHIRToCore(typed)
					if err != nil {
						t.Fatal(err)
					}
					if typed.LanguageContract != string(contract) || program.LanguageContract != string(contract) ||
						projection.LanguageContract != contract || projection.Schema != "pipelang.semantic.v1" ||
						projection.CompilerContract != "pipelang.compiler.v1" || program.CompilerContract != "pipelang.compiler.v1" {
						t.Fatal("contract identity drift")
					}
					generated, err := gobackend.Generate(program)
					if err != nil {
						t.Fatal(err)
					}
					generatedAgain, err := gobackend.Generate(program)
					if err != nil || !bytes.Equal(generated, generatedAgain) {
						t.Fatal("nondeterministic Go")
					}
					function := coreFunctionNamed(t, program, "Continue")
					if function.Body.ImmutableLocal == nil || function.Body.ImmutableLocal.Initializer.Propagate == nil ||
						function.Body.ImmutableLocal.Return.Binary == nil {
						t.Fatal("propagation/checked arithmetic Core missing")
					}
					generatedTests := checkedInheritanceOutcomes(t, program, operation.name)
					// Normalize only language metadata; all identities, spans and bodies must agree.
					typed.LanguageContract = "v0.56.0"
					program.LanguageContract = "v0.56.0"
					projection.LanguageContract = PipeLangLanguageContractV560
					h, err := json.Marshal(typed)
					if err != nil {
						t.Fatal(err)
					}
					c, err := json.Marshal(program)
					if err != nil {
						t.Fatal(err)
					}
					s, err := json.Marshal(projection)
					if err != nil {
						t.Fatal(err)
					}
					if version == 56 {
						baselineHIR, baselineCore, baselineSemantic, baselineGo = h, c, s, generated
						compileAndRunGeneratedGoFiles(t, generated, generatedTests)
					} else if !bytes.Equal(h, baselineHIR) || !bytes.Equal(c, baselineCore) || !bytes.Equal(s, baselineSemantic) || !bytes.Equal(generated, baselineGo) {
						t.Fatal("inherited HIR/Core/semantic/Go bytes differ beyond language metadata")
					}
				})
			}
		})
	}
}

func checkedInheritanceOutcomes(t *testing.T, program coreir.Program, operation string) []byte {
	t.Helper()
	f := coreFunctionNamed(t, program, "Continue")
	carrierType, payload := f.Parameters[0].Type, f.Parameters[1].Type
	type sample struct {
		left, right, want int64
		lf, rf, wf        float64
		incoming, failure coreir.ArithmeticError
	}
	var samples []sample
	switch operation {
	case "add":
		samples = []sample{{left: 40, right: 2, want: 42}, {left: math.MaxInt64, right: 1, failure: coreir.ArithmeticOverflow}, {left: math.MinInt64, right: -1, failure: coreir.ArithmeticOverflow}, {left: math.MaxInt64, right: -1, want: math.MaxInt64 - 1}}
	case "subtract":
		samples = []sample{{left: 40, right: 2, want: 38}, {left: math.MinInt64, right: 1, failure: coreir.ArithmeticOverflow}, {left: math.MaxInt64, right: -1, failure: coreir.ArithmeticOverflow}, {left: math.MinInt64, right: -1, want: math.MinInt64 + 1}}
	case "multiply":
		samples = []sample{{left: 21, right: 2, want: 42}, {left: math.MaxInt64, right: 2, failure: coreir.ArithmeticOverflow}, {left: math.MinInt64, right: -1, failure: coreir.ArithmeticOverflow}, {left: math.MinInt64, right: 1, want: math.MinInt64}}
	case "divide":
		samples = []sample{{lf: 5, rf: 2, wf: 2.5}, {lf: 5, rf: 0, failure: coreir.ArithmeticDivisionByZero}, {lf: 5, rf: math.Copysign(0, -1), failure: coreir.ArithmeticDivisionByZero}, {lf: math.Copysign(0, -1), rf: 2, wf: math.Copysign(0, -1)}, {lf: math.Inf(1), rf: 2, wf: math.Inf(1)}, {lf: math.NaN(), rf: 2, wf: math.NaN()}, {lf: math.SmallestNonzeroFloat64, rf: 1, wf: math.SmallestNonzeroFloat64}}
	}
	// A failed input must win even when the continuation would itself fail.
	for _, failure := range []coreir.ArithmeticError{coreir.ArithmeticOverflow, coreir.ArithmeticDivisionByZero} {
		samples = append(samples, sample{incoming: failure, failure: failure, right: math.MaxInt64})
	}
	var goTests strings.Builder
	goTests.WriteString("package pipelanggenerated\nimport (\"math\"; \"testing\")\nfunc TestInherited(t *testing.T) {\n_ = math.MaxInt64\n")
	for index, tc := range samples {
		left := coreeval.Value{Type: payload, Int: tc.left, Float: tc.lf}
		right := coreeval.Value{Type: payload, Int: tc.right, Float: tc.rf}
		incoming := coreeval.Outcome{OK: tc.incoming == "", Value: left, Error: tc.incoming}
		args := []coreeval.Value{{Type: carrierType, Result: &incoming}, right}
		for _, standalone := range []bool{false, true} {
			var got coreeval.Outcome
			var err error
			if standalone {
				got, err = coreeval.Evaluate(f, args)
			} else {
				got, err = coreeval.EvaluateProgram(program, f.Identity, args)
			}
			if err != nil || got.OK != (tc.failure == "") || got.Error != tc.failure {
				t.Fatalf("sample %d: %#v, %v", index, got, err)
			}
			if !reflect.DeepEqual(got.Value.Type, payload) {
				t.Fatal("payload type changed")
			}
			if operation == "divide" {
				if !(math.IsNaN(got.Value.Float) && math.IsNaN(tc.wf)) && math.Float64bits(got.Value.Float) != math.Float64bits(tc.wf) {
					t.Fatalf("sample %d float = %v", index, got.Value.Float)
				}
			} else if got.Value.Int != tc.want {
				t.Fatalf("sample %d integer = %d", index, got.Value.Int)
			}
		}
		typ, a, b, check := "int64", fmt.Sprint(tc.left), fmt.Sprint(tc.right), fmt.Sprintf("got.Value != %d", tc.want)
		if operation == "divide" {
			typ = "float64"
			a = fmt.Sprintf("math.Float64frombits(%d)", math.Float64bits(tc.lf))
			b = fmt.Sprintf("math.Float64frombits(%d)", math.Float64bits(tc.rf))
			check = fmt.Sprintf("math.Float64bits(got.Value) != %d", math.Float64bits(tc.wf))
			if math.IsNaN(tc.wf) {
				check = "!math.IsNaN(got.Value)"
			}
		}
		fmt.Fprintf(&goTests, "{ got := PipeLangContinue(PipeLangArithmeticResult[%s]{OK:%t,Value:%s,Error:%q},%s); if got.OK != %t || got.Error != %q || %s { t.Fatalf(\"sample %d: %%#v\",got) } }\n", typ, tc.incoming == "", a, tc.incoming, b, tc.failure == "", tc.failure, check, index)
	}
	for _, malformed := range []coreeval.Outcome{
		{OK: true, Value: coreeval.Value{Type: payload}, Error: coreir.ArithmeticOverflow},
		{Value: coreeval.Value{Type: payload}, Error: "unknown"},
		{Value: coreeval.Value{Type: payload, Int: 1, Float: 1}, Error: coreir.ArithmeticOverflow},
	} {
		args := []coreeval.Value{{Type: carrierType, Result: &malformed}, {Type: payload}}
		if _, err := coreeval.EvaluateProgram(program, f.Identity, args); err == nil {
			t.Fatal("program accepted malformed carrier")
		}
		if _, err := coreeval.Evaluate(f, args); err == nil {
			t.Fatal("function accepted malformed carrier")
		}
	}
	typ := "int64"
	if operation == "divide" {
		typ = "float64"
	}
	for _, bad := range []string{`OK:true,Error:PipeLangArithmeticOverflow`, `Error:"unknown"`, `Value:1,Error:PipeLangArithmeticOverflow`} {
		fmt.Fprintf(&goTests, "func(){ defer func(){if recover()==nil {t.Fatal(\"malformed carrier accepted\")}}(); PipeLangContinue(PipeLangArithmeticResult[%s]{%s},1) }()\n", typ, bad)
	}
	goTests.WriteString("}\n")
	return []byte(goTests.String())
}

func TestCheckedPropagationInheritanceRejection(t *testing.T) {
	source := checkedInheritanceSource("int", "+")
	for version := 56; version <= 93; version++ {
		contract := LanguageContract(fmt.Sprintf("v0.%d.0", version))
		t.Run(string(contract), func(t *testing.T) {
			for _, mutation := range []struct{ name, old, new string }{
				{"reversed", "value + operand", "operand + value"}, {"repeated", "value + operand", "value + value"},
				{"literal", "value + operand", "value + 1"}, {"computed", "value + operand", "value + (operand + 1)"},
				{"unary", "value + operand", "-value"}, {"wrong operand type", "int operand)", "float operand)"},
				{"wrong local type", "int value =", "float value ="},
				{"forward reference", "propagate(carrier)", "propagate(value)"},
				{"extra parameter", "int operand)", "int operand, int extra)"},
				{"later propagation", "int value =", "int before = 0; int value ="},
				{"terminal branch", "return value + operand;", "if (true) { return value + operand; } else { return value + operand; }"},
			} {
				t.Run(mutation.name, func(t *testing.T) {
					changed := strings.Replace(source, mutation.old, mutation.new, 1)
					if changed == source {
						t.Fatal("mutation missed")
					}
					input := semanticTestModuleSet("compiler.cursor", []ModuleInput{testModule("compiler.cursor", "invalid.pipe", changed)}, nil)
					input.LanguageContract = contract
					err := AnalyzeSemanticModuleSet(input).Error()
					ds, ok := AsDiagnostics(err)
					if err == nil || !ok || len(ds) == 0 {
						t.Fatal("missing rejection")
					}
					for _, d := range ds {
						if !d.Primary.IsValid() || d.Primary.File != "invalid.pipe" || d.Primary.End > len(changed) {
							t.Fatal("invalid diagnostic span")
						}
					}
				})
			}
			for _, op := range []string{"+", "-", "*"} {
				invalid := checkedInheritanceSource("float", op)
				input := semanticTestModuleSet("compiler.cursor", []ModuleInput{testModule("compiler.cursor", "invalid.pipe", invalid)}, nil)
				input.LanguageContract = contract
				if AnalyzeSemanticModuleSet(input).Error() == nil {
					t.Fatal("unsupported float continuation admitted")
				}
			}
			// Mutate independently admitted Core, bypassing source analysis.
			for _, operation := range checkedInheritanceOperations {
				program := reviewCore(t, contract, checkedInheritanceSource(operation.typ, operation.op), "Continue")
				local := program.Functions[0].Body.ImmutableLocal
				wrong := local.Position
				local.Return.Binary.Right.Parameter = &wrong
				assertAdmissionRejected(t, program, "parameter 1 as right operand")
			}
		})
	}
	for _, version := range []LanguageContract{PipeLangLanguageContractV550, LanguageContract("v0.99.0")} {
		input := semanticTestModuleSet("compiler.cursor", []ModuleInput{testModule("compiler.cursor", "invalid.pipe", source)}, nil)
		input.LanguageContract = version
		if AnalyzeSemanticModuleSet(input).Error() == nil {
			t.Fatal("unsupported source version admitted")
		}
		program := reviewCore(t, PipeLangLanguageContractV560, source, "Continue")
		program.LanguageContract = string(version)
		assertAdmissionRejected(t, program, "")
	}
}

func TestCheckedPropagationInheritancePreservesRelatedForms(t *testing.T) {
	for _, tc := range []struct {
		source, method string
		version        LanguageContract
	}{
		{directCheckedArithmeticPropagationSource, "Continue", PipeLangLanguageContractV550},
		{directCheckedArithmeticPropagationSource, "ContinueFloat", PipeLangLanguageContractV550},
		{checkedArithmeticHelperPropagationSource, "Resolve", PipeLangLanguageContractV540},
		{checkedArithmeticHelperPropagationSource, "ResolveFloat", PipeLangLanguageContractV540},
	} {
		t.Run(tc.method, func(t *testing.T) {
			old := reviewCore(t, tc.version, tc.source, tc.method)
			current := reviewCore(t, PipeLangLanguageContractV820, tc.source, tc.method)
			before, err := gobackend.Generate(old)
			if err != nil {
				t.Fatal(err)
			}
			after, err := gobackend.Generate(current)
			if err != nil || !bytes.Equal(before, after) {
				t.Fatal("inherited generated bytes changed")
			}
		})
	}
}
