// Package gobackend lowers backend-neutral PipeLang Core IR into Go source.
// Its only PipeLang dependency is coreir, which makes a parser/AST-to-Go path
// unavailable to this backend.
package gobackend

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"dockpipe/src/lib/pipelang/coreir"
)

const PackageName = "pipelanggenerated"

type Error struct {
	Code     string
	Function string
	Message  string
}

func (e *Error) Error() string {
	if e == nil {
		return ""
	}
	if e.Function == "" {
		return fmt.Sprintf("%s: %s", e.Code, e.Message)
	}
	return fmt.Sprintf("%s: function %s: %s", e.Code, e.Function, e.Message)
}

// Generate accepts Core IR only and returns deterministic, gofmt-formatted Go.
func Generate(program coreir.Program) ([]byte, error) {
	if (program.LanguageContract != coreir.LanguageContractV010 && program.LanguageContract != coreir.LanguageContractV020 && program.LanguageContract != coreir.LanguageContractV030) || program.CompilerContract != coreir.CompilerContractV1 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("unsupported Core IR contracts language=%q compiler=%q", program.LanguageContract, program.CompilerContract)}
	}
	functions := append([]coreir.Function(nil), program.Functions...)
	sort.SliceStable(functions, func(i, j int) bool {
		left, right := identityKey(functions[i].Identity), identityKey(functions[j].Identity)
		if left != right {
			return left < right
		}
		return functions[i].Name < functions[j].Name
	})
	var out strings.Builder
	out.WriteString("// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.\n")
	out.WriteString("package " + PackageName + "\n\n")
	if programNeedsArithmeticResult(functions) {
		emitArithmeticSupport(&out)
	}
	seen := map[string]string{}
	seenIdentities := map[string]struct{}{}
	for _, function := range functions {
		identity := identityKey(function.Identity)
		if function.Identity.PackageID == "" || function.Identity.Path == "" {
			return nil, backendError(function, "PLGO0001", "function has no semantic identity")
		}
		if _, duplicate := seenIdentities[identity]; duplicate {
			return nil, backendError(function, "PLGO0002", "duplicate semantic function identity")
		}
		seenIdentities[identity] = struct{}{}
		if err := coreir.ValidateFunction(function); err != nil {
			return nil, backendError(function, "PLGO0001", err.Error())
		}
		name := FunctionName(function)
		if previous, ok := seen[name]; ok {
			return nil, backendError(function, "PLGO0002", fmt.Sprintf("Go name %q collides with %s", name, previous))
		}
		seen[name] = identity
		if err := emitFunction(&out, name, function); err != nil {
			return nil, err
		}
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, &Error{Code: "PLGO0003", Message: fmt.Sprintf("format generated Go: %v", err)}
	}
	return formatted, nil
}

func FunctionName(function coreir.Function) string {
	name := strings.TrimSpace(function.Name)
	if name == "" {
		name = finalPathSegment(function.Identity.Path)
	}
	return "PipeLang" + exportedIdentifier(name)
}

func emitFunction(out *strings.Builder, name string, function coreir.Function) error {
	result, err := goType(function.ReturnType)
	if err != nil {
		return backendError(function, "PLGO0001", err.Error())
	}
	fmt.Fprintf(out, "func %s(", name)
	for index, parameter := range function.Parameters {
		if parameter.Position != index {
			return backendError(function, "PLGO0001", "parameters are not in normalized position order")
		}
		parameterType, err := goType(parameter.Type)
		if err != nil {
			return backendError(function, "PLGO0001", err.Error())
		}
		if index > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "p%d %s", index, parameterType)
	}
	fmt.Fprintf(out, ") %s {\n\treturn ", result)
	body, err := emitExpr(function.Body, function.Parameters)
	if err != nil {
		return backendError(function, "PLGO0001", err.Error())
	}
	out.WriteString(body)
	out.WriteString("\n}\n\n")
	return nil
}

func emitExpr(expr coreir.Expr, parameters []coreir.Parameter) (string, error) {
	switch expr.Kind {
	case coreir.ExprLiteral:
		if expr.Literal == nil {
			return "", fmt.Errorf("literal node has no value")
		}
		return emitLiteral(expr.Type, *expr.Literal)
	case coreir.ExprReference:
		if expr.Parameter == nil || *expr.Parameter < 0 || *expr.Parameter >= len(parameters) {
			return "", fmt.Errorf("reference has invalid parameter position")
		}
		return fmt.Sprintf("p%d", *expr.Parameter), nil
	case coreir.ExprUnary:
		if expr.Unary == nil || expr.Unary.Operand == nil {
			return "", fmt.Errorf("unary node is incomplete")
		}
		operand, err := emitExpr(*expr.Unary.Operand, parameters)
		if err != nil {
			return "", err
		}
		if expr.Unary.Operator == coreir.OperatorNegate {
			return "pipelangCheckedNegateInt64(" + operand + ")", nil
		}
		op, ok := mapUnaryOperator(expr.Unary.Operator)
		if !ok {
			return "", fmt.Errorf("unsupported unary operator %q", expr.Unary.Operator)
		}
		return "(" + op + operand + ")", nil
	case coreir.ExprBinary:
		if expr.Binary == nil || expr.Binary.Left == nil || expr.Binary.Right == nil {
			return "", fmt.Errorf("binary node is incomplete")
		}
		switch expr.Binary.Operator {
		case coreir.OperatorAnd, coreir.OperatorOr:
			return "", fmt.Errorf("operator %q is outside the step-7a Go capability slice", expr.Binary.Operator)
		}
		left, err := emitExpr(*expr.Binary.Left, parameters)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(*expr.Binary.Right, parameters)
		if err != nil {
			return "", err
		}
		if expr.Type.Kind == coreir.TypeResult {
			helper, ok := arithmeticHelperName(expr.Binary.Operator)
			if !ok {
				return "", fmt.Errorf("unsupported checked arithmetic operator %q", expr.Binary.Operator)
			}
			return helper + "(" + left + ", " + right + ")", nil
		}
		if requiresEqualOperands(expr.Binary.Operator) && !coreir.TypeEqual(expr.Binary.Left.Type, expr.Binary.Right.Type) {
			return "", fmt.Errorf("operator %q has mismatched Core operand types", expr.Binary.Operator)
		}
		op, ok := mapBinaryOperator(expr.Binary.Operator)
		if !ok {
			return "", fmt.Errorf("unsupported binary operator %q", expr.Binary.Operator)
		}
		return "(" + left + " " + op + " " + right + ")", nil
	default:
		return "", fmt.Errorf("unsupported expression kind %q", expr.Kind)
	}
}

func emitLiteral(typ coreir.Type, literal coreir.Literal) (string, error) {
	if typ.Kind == coreir.TypeNumeric {
		if typ.Numeric == nil {
			return "", fmt.Errorf("numeric literal type has no representation")
		}
		switch {
		case typ.Numeric.Representation == coreir.NumericInteger && typ.Numeric.Bits == 64 && typ.Numeric.Signed:
			return fmt.Sprintf("int64(%d)", literal.Int), nil
		case typ.Numeric.Representation == coreir.NumericBinaryFloat && typ.Numeric.Bits == 64 && !typ.Numeric.Signed:
			return "float64(" + strconv.FormatFloat(literal.Float, 'g', -1, 64) + ")", nil
		default:
			return "", fmt.Errorf("unsupported numeric literal representation %q/%d", typ.Numeric.Representation, typ.Numeric.Bits)
		}
	}
	if typ.Kind != coreir.TypePrimitive {
		return "", fmt.Errorf("literal type %q is unsupported", typ.Kind)
	}
	switch typ.Primitive {
	case coreir.PrimitiveString:
		return strconv.Quote(literal.String), nil
	case coreir.PrimitiveBool:
		return strconv.FormatBool(literal.Bool), nil
	default:
		return "", fmt.Errorf("unsupported primitive literal type %q", typ.Primitive)
	}
}

func goType(typ coreir.Type) (string, error) {
	if typ.Kind == coreir.TypeResult {
		if typ.Result == nil || typ.Result.Failure.Kind != coreir.TypeArithmeticError {
			return "", fmt.Errorf("Go checked-arithmetic backend supports ArithmeticError Result failures only")
		}
		success, err := goType(typ.Result.Success)
		if err != nil {
			return "", err
		}
		return "PipeLangArithmeticResult[" + success + "]", nil
	}
	if typ.Kind == coreir.TypeNumeric {
		if typ.Numeric == nil {
			return "", fmt.Errorf("numeric Core type has no representation")
		}
		switch {
		case typ.Numeric.Representation == coreir.NumericInteger && typ.Numeric.Bits == 64 && typ.Numeric.Signed:
			return "int64", nil
		case typ.Numeric.Representation == coreir.NumericBinaryFloat && typ.Numeric.Bits == 64 && !typ.Numeric.Signed:
			return "float64", nil
		default:
			return "", fmt.Errorf("Go checked-arithmetic backend does not support numeric representation %q/%d", typ.Numeric.Representation, typ.Numeric.Bits)
		}
	}
	if typ.Kind != coreir.TypePrimitive {
		return "", fmt.Errorf("Go checked-arithmetic backend supports primitive, fixed numeric, and arithmetic Result types only, got %q", typ.Kind)
	}
	switch typ.Primitive {
	case coreir.PrimitiveString:
		return "string", nil
	case coreir.PrimitiveBool:
		return "bool", nil
	default:
		return "", fmt.Errorf("unsupported primitive type %q", typ.Primitive)
	}
}

func mapUnaryOperator(operator coreir.Operator) (string, bool) {
	switch operator {
	case coreir.OperatorNot:
		return "!", true
	case coreir.OperatorNegate:
		return "-", true
	default:
		return "", false
	}
}

func requiresEqualOperands(operator coreir.Operator) bool {
	switch operator {
	case coreir.OperatorEqual, coreir.OperatorNotEqual, coreir.OperatorLessThan, coreir.OperatorLessOrEqual, coreir.OperatorGreaterThan, coreir.OperatorGreaterOrEqual:
		return true
	default:
		return false
	}
}

func mapBinaryOperator(operator coreir.Operator) (string, bool) {
	switch operator {
	case coreir.OperatorAdd:
		return "+", true
	case coreir.OperatorSubtract:
		return "-", true
	case coreir.OperatorMultiply:
		return "*", true
	case coreir.OperatorEqual:
		return "==", true
	case coreir.OperatorNotEqual:
		return "!=", true
	case coreir.OperatorLessThan:
		return "<", true
	case coreir.OperatorLessOrEqual:
		return "<=", true
	case coreir.OperatorGreaterThan:
		return ">", true
	case coreir.OperatorGreaterOrEqual:
		return ">=", true
	default:
		return "", false
	}
}

func programNeedsArithmeticResult(functions []coreir.Function) bool {
	for _, function := range functions {
		if function.ReturnType.Kind == coreir.TypeResult {
			return true
		}
	}
	return false
}

func arithmeticHelperName(operator coreir.Operator) (string, bool) {
	switch operator {
	case coreir.OperatorAdd:
		return "pipelangCheckedAddInt64", true
	case coreir.OperatorSubtract:
		return "pipelangCheckedSubtractInt64", true
	case coreir.OperatorMultiply:
		return "pipelangCheckedMultiplyInt64", true
	case coreir.OperatorDivide:
		return "pipelangCheckedDivideBinary64", true
	default:
		return "", false
	}
}

func emitArithmeticSupport(out *strings.Builder) {
	out.WriteString(`type PipeLangArithmeticError string

const (
	PipeLangArithmeticOverflow PipeLangArithmeticError = "overflow"
	PipeLangArithmeticDivisionByZero PipeLangArithmeticError = "division_by_zero"
)

type PipeLangArithmeticResult[T any] struct {
	OK bool
	Value T
	Error PipeLangArithmeticError
}

func pipelangCheckedAddInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if (right > 0 && left > maximum-right) || (right < 0 && left < minimum-right) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: left + right}
}

func pipelangCheckedSubtractInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if (right < 0 && left > maximum+right) || (right > 0 && left < minimum+right) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: left - right}
}

func pipelangCheckedMultiplyInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if left == 0 || right == 0 {
		return PipeLangArithmeticResult[int64]{OK: true}
	}
	if (left == minimum && right == -1) || (right == minimum && left == -1) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	value := left * right
	if value/right != left {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: value}
}

func pipelangCheckedNegateInt64(value int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if value == minimum {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: -value}
}

func pipelangCheckedDivideBinary64(left, right float64) PipeLangArithmeticResult[float64] {
	if right == 0 {
		return PipeLangArithmeticResult[float64]{Error: PipeLangArithmeticDivisionByZero}
	}
	return PipeLangArithmeticResult[float64]{OK: true, Value: left / right}
}

`)
}

func backendError(function coreir.Function, code, message string) error {
	return &Error{Code: code, Function: identityKey(function.Identity), Message: message}
}

func identityKey(identity coreir.SemanticIdentity) string {
	return identity.PackageID + ":" + identity.Path
}

func finalPathSegment(path string) string {
	if index := strings.LastIndexByte(path, '.'); index >= 0 {
		return path[index+1:]
	}
	return path
}

func exportedIdentifier(value string) string {
	var out strings.Builder
	upperNext := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if out.Len() == 0 && unicode.IsDigit(r) {
			out.WriteRune('X')
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		}
		out.WriteRune(r)
	}
	if out.Len() == 0 {
		return "Function"
	}
	return out.String()
}
