// Package gobackend lowers backend-neutral PipeLang Core IR into Go source.
// Its only PipeLang dependency is coreir, which makes a parser/AST-to-Go path
// unavailable to this backend.
package gobackend

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"dockpipe/src/lib/pipelang/coreir"
)

const PackageName = "pipelanggenerated"

type Error struct {
	Code     string
	Function string
	Message  string
}

func (e *Error) Error() string {
	if e == nil {
		return ""
	}
	if e.Function == "" {
		return fmt.Sprintf("%s: %s", e.Code, e.Message)
	}
	return fmt.Sprintf("%s: function %s: %s", e.Code, e.Function, e.Message)
}

// Generate accepts Core IR only and returns deterministic, gofmt-formatted Go.
func Generate(program coreir.Program) ([]byte, error) {
	if (program.LanguageContract != coreir.LanguageContractV010 && program.LanguageContract != coreir.LanguageContractV020 && program.LanguageContract != coreir.LanguageContractV030 && program.LanguageContract != coreir.LanguageContractV040 && program.LanguageContract != coreir.LanguageContractV050 && program.LanguageContract != coreir.LanguageContractV060 && program.LanguageContract != coreir.LanguageContractV070 && program.LanguageContract != coreir.LanguageContractV080 && program.LanguageContract != coreir.LanguageContractV090 && program.LanguageContract != coreir.LanguageContractV100 && program.LanguageContract != coreir.LanguageContractV110 && program.LanguageContract != coreir.LanguageContractV120 && program.LanguageContract != coreir.LanguageContractV130 && program.LanguageContract != coreir.LanguageContractV140 && program.LanguageContract != coreir.LanguageContractV150 && program.LanguageContract != coreir.LanguageContractV160 && program.LanguageContract != coreir.LanguageContractV170 && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230) || program.CompilerContract != coreir.CompilerContractV1 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("unsupported Core IR contracts language=%q compiler=%q", program.LanguageContract, program.CompilerContract)}
	}
	functions := append([]coreir.Function(nil), program.Functions...)
	sort.SliceStable(functions, func(i, j int) bool {
		left, right := identityKey(functions[i].Identity), identityKey(functions[j].Identity)
		if left != right {
			return left < right
		}
		return functions[i].Name < functions[j].Name
	})
	for _, function := range functions {
		if err := coreir.ValidateFunction(function); err != nil {
			return nil, backendError(function, "PLGO0001", err.Error())
		}
	}
	var out strings.Builder
	out.WriteString("// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.\n")
	out.WriteString("package " + PackageName + "\n\n")
	needsText := programNeedsTextSupport(functions)
	needsCaseFoldedText := programNeedsCaseFoldedText(functions)
	needsOptional := programNeedsOptionalSupport(functions)
	needsOptionalDefault := programNeedsOptionalDefault(functions)
	needsRecordOptional := programNeedsRecordOptionalSupport(functions)
	needsList := programNeedsListSupport(functions)
	needsListCount := programNeedsListCount(functions)
	needsListAppend := programNeedsListAppend(functions)
	needsListAt := programNeedsListAt(functions)
	needsListFindByText := programNeedsListFindByText(functions)
	needsListFilterByText := programNeedsListFilterByText(functions)
	needsListFilterContainsCaseFolded := programNeedsListFilterContainsCaseFolded(functions)
	needsSnapshotResult := programNeedsSnapshotResult(functions)
	optionalTypeName := optionalGoTypeName(functions)
	if needsOptional && program.LanguageContract != coreir.LanguageContractV130 && program.LanguageContract != coreir.LanguageContractV140 && program.LanguageContract != coreir.LanguageContractV150 && program.LanguageContract != coreir.LanguageContractV160 && program.LanguageContract != coreir.LanguageContractV170 && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("primitive Optional Core requires language contract %q", coreir.LanguageContractV130)}
	}
	if needsOptionalDefault && program.LanguageContract != coreir.LanguageContractV140 && program.LanguageContract != coreir.LanguageContractV150 && program.LanguageContract != coreir.LanguageContractV160 && program.LanguageContract != coreir.LanguageContractV170 && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("primitive Optional defaulting Core requires language contract %q", coreir.LanguageContractV140)}
	}
	if needsRecordOptional && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("primitive-record Optional Core requires language contract %q", coreir.LanguageContractV180)}
	}
	if needsList && program.LanguageContract != coreir.LanguageContractV150 && program.LanguageContract != coreir.LanguageContractV160 && program.LanguageContract != coreir.LanguageContractV170 && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list Core requires language contract %q", coreir.LanguageContractV150)}
	}
	if needsListCount && program.LanguageContract != coreir.LanguageContractV160 && program.LanguageContract != coreir.LanguageContractV170 && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list count Core requires language contract %q", coreir.LanguageContractV160)}
	}
	if needsListAppend && program.LanguageContract != coreir.LanguageContractV170 && program.LanguageContract != coreir.LanguageContractV180 && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list append Core requires language contract %q", coreir.LanguageContractV170)}
	}
	if needsSnapshotResult && program.LanguageContract != coreir.LanguageContractV190 && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("snapshot Result Core requires language contract %q", coreir.LanguageContractV190)}
	}
	if needsListAt && program.LanguageContract != coreir.LanguageContractV200 && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list at Core requires language contract %q", coreir.LanguageContractV200)}
	}
	if needsListFindByText && program.LanguageContract != coreir.LanguageContractV210 && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list find_by Core requires language contract %q", coreir.LanguageContractV210)}
	}
	if needsListFilterByText && program.LanguageContract != coreir.LanguageContractV220 && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list filter_by Core requires language contract %q", coreir.LanguageContractV220)}
	}
	if needsCaseFoldedText && program.LanguageContract != coreir.LanguageContractV240 && program.LanguageContract != coreir.LanguageContractV230 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("contains_casefolded Core requires language contract %q", coreir.LanguageContractV230)}
	}
	if needsListFilterContainsCaseFolded && program.LanguageContract != coreir.LanguageContractV240 {
		return nil, &Error{Code: "PLGO0001", Message: fmt.Sprintf("record-list filter_contains_casefolded Core requires language contract %q", coreir.LanguageContractV240)}
	}
	if needsText {
		if needsCaseFoldedText {
			out.WriteString("import (\n\t\"strings\"\n\t\"unicode/utf8\"\n)\n\n")
		} else {
			out.WriteString("import \"unicode/utf8\"\n\n")
		}
		emitTextSupport(&out, needsCaseFoldedText)
	}
	if programNeedsArithmeticResult(functions) {
		emitArithmeticSupport(&out)
	}
	records, err := collectRecordTypes(functions)
	if err != nil {
		return nil, &Error{Code: "PLGO0001", Message: err.Error()}
	}
	if needsOptional {
		emitOptionalSupport(&out, needsText, needsOptionalDefault, needsRecordOptional, optionalTypeName, records)
	}
	for _, record := range records {
		emitRecordType(&out, record, programConstructsRecord(functions, record), optionalTypeName)
	}
	lists, err := collectListTypes(functions)
	if err != nil {
		return nil, &Error{Code: "PLGO0001", Message: err.Error()}
	}
	for _, list := range lists {
		emitListSupport(&out, list, programAppendsList(functions, list), programIndexesList(functions, list), programFindsListByText(functions, list), programFiltersListByText(functions, list), programFiltersListContainsCaseFolded(functions, list), optionalTypeName)
	}
	results, err := collectSnapshotResultTypes(functions)
	if err != nil {
		return nil, &Error{Code: "PLGO0001", Message: err.Error()}
	}
	if len(results) > 0 {
		emitSnapshotResultType(&out)
		for _, result := range results {
			emitSnapshotResultSupport(&out, result)
		}
	}
	seen := map[string]string{}
	seenIdentities := map[string]struct{}{}
	for _, function := range functions {
		identity := identityKey(function.Identity)
		if function.Identity.PackageID == "" || function.Identity.Path == "" {
			return nil, backendError(function, "PLGO0001", "function has no semantic identity")
		}
		if _, duplicate := seenIdentities[identity]; duplicate {
			return nil, backendError(function, "PLGO0002", "duplicate semantic function identity")
		}
		seenIdentities[identity] = struct{}{}
		if err := coreir.ValidateFunction(function); err != nil {
			return nil, backendError(function, "PLGO0001", err.Error())
		}
		name := FunctionName(function)
		if previous, ok := seen[name]; ok {
			return nil, backendError(function, "PLGO0002", fmt.Sprintf("Go name %q collides with %s", name, previous))
		}
		seen[name] = identity
		if err := emitFunction(&out, name, function, optionalTypeName); err != nil {
			return nil, err
		}
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, &Error{Code: "PLGO0003", Message: fmt.Sprintf("format generated Go: %v", err)}
	}
	return formatted, nil
}

func FunctionName(function coreir.Function) string {
	name := strings.TrimSpace(function.Name)
	if name == "" {
		name = finalPathSegment(function.Identity.Path)
	}
	return "PipeLang" + exportedIdentifier(name)
}

func emitFunction(out *strings.Builder, name string, function coreir.Function, optionalTypeName string) error {
	result, err := goType(function.ReturnType, optionalTypeName)
	if err != nil {
		return backendError(function, "PLGO0001", err.Error())
	}
	fmt.Fprintf(out, "func %s(", name)
	for index, parameter := range function.Parameters {
		if parameter.Position != index {
			return backendError(function, "PLGO0001", "parameters are not in normalized position order")
		}
		parameterType, err := goType(parameter.Type, optionalTypeName)
		if err != nil {
			return backendError(function, "PLGO0001", err.Error())
		}
		if index > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "p%d %s", index, parameterType)
	}
	fmt.Fprintf(out, ") %s {\n", result)
	for index, parameter := range function.Parameters {
		if parameter.Type.Kind == coreir.TypeRecord {
			fmt.Fprintf(out, "\t%s(p%d)\n", recordValidationName(parameter.Type), index)
		}
		if parameter.Type.Kind == coreir.TypeOptional {
			fmt.Fprintf(out, "\tpipelangValidateOptional(p%d)\n", index)
		}
		if parameter.Type.Kind == coreir.TypeList {
			fmt.Fprintf(out, "\t%s(p%d)\n", listValidationName(parameter.Type), index)
		}
		if isSnapshotResultType(parameter.Type) {
			fmt.Fprintf(out, "\t%s(p%d)\n", snapshotResultValidationName(parameter.Type), index)
		}
	}
	out.WriteString("\treturn ")
	body, err := emitExpr(function.Body, function.Parameters, optionalTypeName)
	if err != nil {
		return backendError(function, "PLGO0001", err.Error())
	}
	out.WriteString(body)
	out.WriteString("\n}\n\n")
	return nil
}

func emitExpr(expr coreir.Expr, parameters []coreir.Parameter, optionalTypeName string) (string, error) {
	switch expr.Kind {
	case coreir.ExprLiteral:
		if expr.Literal == nil {
			return "", fmt.Errorf("literal node has no value")
		}
		return emitLiteral(expr.Type, *expr.Literal)
	case coreir.ExprReference:
		if expr.Parameter == nil || *expr.Parameter < 0 || *expr.Parameter >= len(parameters) {
			return "", fmt.Errorf("reference has invalid parameter position")
		}
		if expr.Type.Kind == coreir.TypeList {
			return fmt.Sprintf("%s(p%d)", listCloneName(expr.Type), *expr.Parameter), nil
		}
		if isSnapshotResultType(expr.Type) {
			return fmt.Sprintf("%s(p%d)", snapshotResultCloneName(expr.Type), *expr.Parameter), nil
		}
		return fmt.Sprintf("p%d", *expr.Parameter), nil
	case coreir.ExprUnary:
		if expr.Unary == nil || expr.Unary.Operand == nil {
			return "", fmt.Errorf("unary node is incomplete")
		}
		operand, err := emitExpr(*expr.Unary.Operand, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		if expr.Unary.Operator == coreir.OperatorNegate {
			return "pipelangCheckedNegateInt64(" + operand + ")", nil
		}
		op, ok := mapUnaryOperator(expr.Unary.Operator)
		if !ok {
			return "", fmt.Errorf("unsupported unary operator %q", expr.Unary.Operator)
		}
		return "(" + op + operand + ")", nil
	case coreir.ExprBinary:
		if expr.Binary == nil || expr.Binary.Left == nil || expr.Binary.Right == nil {
			return "", fmt.Errorf("binary node is incomplete")
		}
		switch expr.Binary.Operator {
		case coreir.OperatorAnd, coreir.OperatorOr:
			return "", fmt.Errorf("operator %q is outside the step-7a Go capability slice", expr.Binary.Operator)
		}
		left, err := emitExpr(*expr.Binary.Left, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		right, err := emitExpr(*expr.Binary.Right, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		if isTextType(expr.Binary.Left.Type) && isTextType(expr.Binary.Right.Type) {
			switch expr.Binary.Operator {
			case coreir.OperatorAdd:
				return "pipelangConcatText(" + left + ", " + right + ")", nil
			case coreir.OperatorEqual:
				return "(pipelangCompareOrdinalText(" + left + ", " + right + ") == 0)", nil
			case coreir.OperatorNotEqual:
				return "(pipelangCompareOrdinalText(" + left + ", " + right + ") != 0)", nil
			case coreir.OperatorLessThan:
				return "(pipelangCompareOrdinalText(" + left + ", " + right + ") < 0)", nil
			case coreir.OperatorLessOrEqual:
				return "(pipelangCompareOrdinalText(" + left + ", " + right + ") <= 0)", nil
			case coreir.OperatorGreaterThan:
				return "(pipelangCompareOrdinalText(" + left + ", " + right + ") > 0)", nil
			case coreir.OperatorGreaterOrEqual:
				return "(pipelangCompareOrdinalText(" + left + ", " + right + ") >= 0)", nil
			}
		}
		if expr.Type.Kind == coreir.TypeResult {
			helper, ok := arithmeticHelperName(expr.Binary.Operator)
			if !ok {
				return "", fmt.Errorf("unsupported checked arithmetic operator %q", expr.Binary.Operator)
			}
			return helper + "(" + left + ", " + right + ")", nil
		}
		if requiresEqualOperands(expr.Binary.Operator) && !coreir.TypeEqual(expr.Binary.Left.Type, expr.Binary.Right.Type) {
			return "", fmt.Errorf("operator %q has mismatched Core operand types", expr.Binary.Operator)
		}
		op, ok := mapBinaryOperator(expr.Binary.Operator)
		if !ok {
			return "", fmt.Errorf("unsupported binary operator %q", expr.Binary.Operator)
		}
		return "(" + left + " " + op + " " + right + ")", nil
	case coreir.ExprTextContainsCaseFolded:
		if expr.TextContains == nil || expr.TextContains.Value == nil || expr.TextContains.Query == nil {
			return "", fmt.Errorf("contains_casefolded expression is incomplete")
		}
		value, err := emitExpr(*expr.TextContains.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		query, err := emitExpr(*expr.TextContains.Query, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "pipelangContainsCaseFoldedText(" + value + ", " + query + ")", nil
	case coreir.ExprFieldProjection:
		if expr.Field == nil || expr.Field.Receiver == nil {
			return "", fmt.Errorf("field projection is incomplete")
		}
		receiverType := expr.Field.Receiver.Type
		if receiverType.Kind != coreir.TypeRecord || receiverType.Record == nil || expr.Field.Position < 0 || expr.Field.Position >= len(receiverType.Record.Fields) {
			return "", fmt.Errorf("field projection has an invalid record schema or position")
		}
		receiver, err := emitExpr(*expr.Field.Receiver, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return receiver + "." + recordGoFieldNames(receiverType)[expr.Field.Position], nil
	case coreir.ExprRecordConstruct:
		if expr.Record == nil || expr.Type.Kind != coreir.TypeRecord || expr.Type.Record == nil || len(expr.Record.Fields) != len(expr.Type.Record.Fields) {
			return "", fmt.Errorf("record construction is incomplete or does not match its schema")
		}
		arguments := make([]string, 0, len(expr.Record.Fields))
		for position, initialized := range expr.Record.Fields {
			if initialized.Value == nil || initialized.Position != position {
				return "", fmt.Errorf("record construction field %d is incomplete or out of order", position)
			}
			value, err := emitExpr(*initialized.Value, parameters, optionalTypeName)
			if err != nil {
				return "", err
			}
			arguments = append(arguments, value)
		}
		return recordConstructionName(expr.Type) + "(" + strings.Join(arguments, ", ") + ")", nil
	case coreir.ExprOptionalSome:
		if expr.Some == nil || expr.Some.Value == nil || expr.Type.Kind != coreir.TypeOptional {
			return "", fmt.Errorf("optional some expression is incomplete")
		}
		value, err := emitExpr(*expr.Some.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "pipelangSomeValue(" + value + ")", nil
	case coreir.ExprOptionalNone:
		if expr.None == nil || expr.Type.Kind != coreir.TypeOptional || expr.Type.Optional == nil {
			return "", fmt.Errorf("optional none expression is incomplete")
		}
		valueType, err := goType(expr.Type.Optional.Value, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "pipelangNoneValue[" + valueType + "]()", nil
	case coreir.ExprOptionalHasValue:
		if expr.HasValue == nil || expr.HasValue.Value == nil {
			return "", fmt.Errorf("optional has_value expression is incomplete")
		}
		value, err := emitExpr(*expr.HasValue.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "pipelangHasValue(" + value + ")", nil
	case coreir.ExprOptionalValueOr:
		if expr.ValueOr == nil || expr.ValueOr.Value == nil || expr.ValueOr.Fallback == nil {
			return "", fmt.Errorf("optional value_or expression is incomplete")
		}
		value, err := emitExpr(*expr.ValueOr.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		fallback, err := emitExpr(*expr.ValueOr.Fallback, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "pipelangValueOr(" + value + ", " + fallback + ")", nil
	case coreir.ExprListEmpty:
		if expr.ListEmpty == nil || expr.Type.Kind != coreir.TypeList {
			return "", fmt.Errorf("list empty expression is incomplete")
		}
		return listEmptyName(expr.Type) + "()", nil
	case coreir.ExprListSingleton:
		if expr.ListOne == nil || expr.ListOne.Value == nil || expr.Type.Kind != coreir.TypeList {
			return "", fmt.Errorf("list singleton expression is incomplete")
		}
		value, err := emitExpr(*expr.ListOne.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return listSingletonName(expr.Type) + "(" + value + ")", nil
	case coreir.ExprListCount:
		if expr.ListCount == nil || expr.ListCount.Value == nil || expr.ListCount.Value.Kind != coreir.ExprReference || expr.ListCount.Value.Parameter == nil {
			return "", fmt.Errorf("list count expression is incomplete")
		}
		return fmt.Sprintf("int64(len(p%d))", *expr.ListCount.Value.Parameter), nil
	case coreir.ExprListAppend:
		if expr.ListAppend == nil || expr.ListAppend.Values == nil || expr.ListAppend.Value == nil || expr.ListAppend.Values.Kind != coreir.ExprReference || expr.ListAppend.Values.Parameter == nil || expr.ListAppend.Value.Kind != coreir.ExprReference || expr.ListAppend.Value.Parameter == nil {
			return "", fmt.Errorf("list append expression is incomplete")
		}
		return fmt.Sprintf("%s(p%d, p%d)", listAppendName(expr.Type), *expr.ListAppend.Values.Parameter, *expr.ListAppend.Value.Parameter), nil
	case coreir.ExprListAt:
		if expr.ListAt == nil || expr.ListAt.Values == nil || expr.ListAt.Index == nil || expr.ListAt.Values.Kind != coreir.ExprReference || expr.ListAt.Values.Parameter == nil || expr.ListAt.Index.Kind != coreir.ExprReference || expr.ListAt.Index.Parameter == nil || expr.ListAt.Values.Type.Kind != coreir.TypeList {
			return "", fmt.Errorf("list at expression is incomplete")
		}
		return fmt.Sprintf("%s(p%d, p%d)", listAtName(expr.ListAt.Values.Type), *expr.ListAt.Values.Parameter, *expr.ListAt.Index.Parameter), nil
	case coreir.ExprListFindByText:
		if expr.ListFind == nil || expr.ListFind.Values == nil || expr.ListFind.Key == nil || expr.ListFind.Values.Kind != coreir.ExprReference || expr.ListFind.Values.Parameter == nil || expr.ListFind.Key.Kind != coreir.ExprReference || expr.ListFind.Key.Parameter == nil || expr.ListFind.Values.Type.Kind != coreir.TypeList {
			return "", fmt.Errorf("list find_by expression is incomplete")
		}
		return fmt.Sprintf("%s(p%d, p%d)", listFindByTextName(expr.ListFind.Values.Type, *expr.ListFind), *expr.ListFind.Values.Parameter, *expr.ListFind.Key.Parameter), nil
	case coreir.ExprListFilterByText:
		if expr.ListFilter == nil || expr.ListFilter.Values == nil || expr.ListFilter.Key == nil || expr.ListFilter.Values.Kind != coreir.ExprReference || expr.ListFilter.Values.Parameter == nil || expr.ListFilter.Key.Kind != coreir.ExprReference || expr.ListFilter.Key.Parameter == nil || expr.ListFilter.Values.Type.Kind != coreir.TypeList {
			return "", fmt.Errorf("list filter_by expression is incomplete")
		}
		return fmt.Sprintf("%s(p%d, p%d)", listFilterByTextName(expr.ListFilter.Values.Type, *expr.ListFilter), *expr.ListFilter.Values.Parameter, *expr.ListFilter.Key.Parameter), nil
	case coreir.ExprListFilterContainsCaseFolded:
		filter := expr.ListFilterContainsCaseFolded
		if filter == nil || filter.Values == nil || filter.Query == nil || filter.Values.Kind != coreir.ExprReference || filter.Values.Parameter == nil || filter.Query.Kind != coreir.ExprReference || filter.Query.Parameter == nil || filter.Values.Type.Kind != coreir.TypeList {
			return "", fmt.Errorf("list filter_contains_casefolded expression is incomplete")
		}
		return fmt.Sprintf("%s(p%d, p%d)", listFilterContainsCaseFoldedName(filter.Values.Type, *filter), *filter.Values.Parameter, *filter.Query.Parameter), nil
	case coreir.ExprResultOK:
		if expr.ResultOK == nil || expr.ResultOK.Value == nil || !isSnapshotResultType(expr.Type) {
			return "", fmt.Errorf("result ok expression is incomplete")
		}
		value, err := emitExpr(*expr.ResultOK.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return snapshotResultOKName(expr.Type) + "(" + value + ")", nil
	case coreir.ExprResultErr:
		if expr.ResultErr == nil || expr.ResultErr.Error == nil || !isSnapshotResultType(expr.Type) {
			return "", fmt.Errorf("result err expression is incomplete")
		}
		failure, err := emitExpr(*expr.ResultErr.Error, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return snapshotResultErrName(expr.Type) + "(" + failure + ")", nil
	case coreir.ExprResultIsOK:
		if expr.ResultIsOK == nil || expr.ResultIsOK.Value == nil || !isSnapshotResultType(expr.ResultIsOK.Value.Type) {
			return "", fmt.Errorf("result is_ok expression is incomplete")
		}
		value, err := emitExpr(*expr.ResultIsOK.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return snapshotResultIsOKName(expr.ResultIsOK.Value.Type) + "(" + value + ")", nil
	case coreir.ExprResultSuccessOr:
		if expr.SuccessOr == nil || expr.SuccessOr.Value == nil || expr.SuccessOr.Fallback == nil || !isSnapshotResultType(expr.SuccessOr.Value.Type) {
			return "", fmt.Errorf("result success_or expression is incomplete")
		}
		value, err := emitExpr(*expr.SuccessOr.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		fallback, err := emitExpr(*expr.SuccessOr.Fallback, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return snapshotResultSuccessOrName(expr.SuccessOr.Value.Type) + "(" + value + ", " + fallback + ")", nil
	case coreir.ExprResultFailureOr:
		if expr.FailureOr == nil || expr.FailureOr.Value == nil || expr.FailureOr.Fallback == nil || !isSnapshotResultType(expr.FailureOr.Value.Type) {
			return "", fmt.Errorf("result failure_or expression is incomplete")
		}
		value, err := emitExpr(*expr.FailureOr.Value, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		fallback, err := emitExpr(*expr.FailureOr.Fallback, parameters, optionalTypeName)
		if err != nil {
			return "", err
		}
		return snapshotResultFailureOrName(expr.FailureOr.Value.Type) + "(" + value + ", " + fallback + ")", nil
	default:
		return "", fmt.Errorf("unsupported expression kind %q", expr.Kind)
	}
}

func emitLiteral(typ coreir.Type, literal coreir.Literal) (string, error) {
	if typ.Kind == coreir.TypeNumeric {
		if typ.Numeric == nil {
			return "", fmt.Errorf("numeric literal type has no representation")
		}
		switch {
		case typ.Numeric.Representation == coreir.NumericInteger && typ.Numeric.Bits == 64 && typ.Numeric.Signed:
			return fmt.Sprintf("int64(%d)", literal.Int), nil
		case typ.Numeric.Representation == coreir.NumericBinaryFloat && typ.Numeric.Bits == 64 && !typ.Numeric.Signed:
			return "float64(" + strconv.FormatFloat(literal.Float, 'g', -1, 64) + ")", nil
		default:
			return "", fmt.Errorf("unsupported numeric literal representation %q/%d", typ.Numeric.Representation, typ.Numeric.Bits)
		}
	}
	if typ.Kind != coreir.TypePrimitive {
		return "", fmt.Errorf("literal type %q is unsupported", typ.Kind)
	}
	switch typ.Primitive {
	case coreir.PrimitiveString:
		return strconv.Quote(literal.String), nil
	case coreir.PrimitiveBool:
		return strconv.FormatBool(literal.Bool), nil
	default:
		return "", fmt.Errorf("unsupported primitive literal type %q", typ.Primitive)
	}
}

func goType(typ coreir.Type, optionalTypeName string) (string, error) {
	if typ.Kind == coreir.TypeList {
		if typ.List == nil || typ.List.Element.Kind != coreir.TypeRecord {
			return "", fmt.Errorf("Go list backend requires one record element type")
		}
		element, err := goType(typ.List.Element, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "[]" + element, nil
	}
	if typ.Kind == coreir.TypeOptional {
		if typ.Optional == nil {
			return "", fmt.Errorf("Go Optional backend requires a value type")
		}
		value, err := goType(typ.Optional.Value, optionalTypeName)
		if err != nil {
			return "", err
		}
		return optionalTypeName + "[" + value + "]", nil
	}
	if typ.Kind == coreir.TypeRecord {
		if typ.Record == nil || typ.Identity == nil || typ.Identity.PackageID == "" || typ.Identity.Path == "" {
			return "", fmt.Errorf("Go record backend requires an identified record schema")
		}
		return recordGoTypeName(typ), nil
	}
	if typ.Kind == coreir.TypeResult {
		if typ.Result == nil {
			return "", fmt.Errorf("Go Result backend requires success and failure types")
		}
		success, err := goType(typ.Result.Success, optionalTypeName)
		if err != nil {
			return "", err
		}
		if typ.Result.Failure.Kind == coreir.TypeArithmeticError {
			return "PipeLangArithmeticResult[" + success + "]", nil
		}
		if !isSnapshotResultType(typ) {
			return "", fmt.Errorf("Go Result backend supports only arithmetic and snapshot Result shapes")
		}
		failure, err := goType(typ.Result.Failure, optionalTypeName)
		if err != nil {
			return "", err
		}
		return "PipeLangResult[" + success + ", " + failure + "]", nil
	}
	if typ.Kind == coreir.TypeNumeric {
		if typ.Numeric == nil {
			return "", fmt.Errorf("numeric Core type has no representation")
		}
		switch {
		case typ.Numeric.Representation == coreir.NumericInteger && typ.Numeric.Bits == 64 && typ.Numeric.Signed:
			return "int64", nil
		case typ.Numeric.Representation == coreir.NumericBinaryFloat && typ.Numeric.Bits == 64 && !typ.Numeric.Signed:
			return "float64", nil
		default:
			return "", fmt.Errorf("Go checked-arithmetic backend does not support numeric representation %q/%d", typ.Numeric.Representation, typ.Numeric.Bits)
		}
	}
	if typ.Kind != coreir.TypePrimitive {
		return "", fmt.Errorf("Go checked-arithmetic backend supports primitive, fixed numeric, and arithmetic Result types only, got %q", typ.Kind)
	}
	switch typ.Primitive {
	case coreir.PrimitiveString:
		return "string", nil
	case coreir.PrimitiveBool:
		return "bool", nil
	default:
		return "", fmt.Errorf("unsupported primitive type %q", typ.Primitive)
	}
}

func mapUnaryOperator(operator coreir.Operator) (string, bool) {
	switch operator {
	case coreir.OperatorNot:
		return "!", true
	case coreir.OperatorNegate:
		return "-", true
	default:
		return "", false
	}
}

func requiresEqualOperands(operator coreir.Operator) bool {
	switch operator {
	case coreir.OperatorEqual, coreir.OperatorNotEqual, coreir.OperatorLessThan, coreir.OperatorLessOrEqual, coreir.OperatorGreaterThan, coreir.OperatorGreaterOrEqual:
		return true
	default:
		return false
	}
}

func mapBinaryOperator(operator coreir.Operator) (string, bool) {
	switch operator {
	case coreir.OperatorAdd:
		return "+", true
	case coreir.OperatorSubtract:
		return "-", true
	case coreir.OperatorMultiply:
		return "*", true
	case coreir.OperatorEqual:
		return "==", true
	case coreir.OperatorNotEqual:
		return "!=", true
	case coreir.OperatorLessThan:
		return "<", true
	case coreir.OperatorLessOrEqual:
		return "<=", true
	case coreir.OperatorGreaterThan:
		return ">", true
	case coreir.OperatorGreaterOrEqual:
		return ">=", true
	default:
		return "", false
	}
}

func isTextType(value coreir.Type) bool {
	return value.Kind == coreir.TypePrimitive && value.Primitive == coreir.PrimitiveString
}

func programNeedsTextSupport(functions []coreir.Function) bool {
	for _, function := range functions {
		if typeNeedsTextSupport(function.ReturnType) || expressionNeedsTextSupport(function.Body) {
			return true
		}
		for _, parameter := range function.Parameters {
			if typeNeedsTextSupport(parameter.Type) {
				return true
			}
		}
	}
	return false
}

func typeNeedsTextSupport(value coreir.Type) bool {
	if isTextType(value) {
		return true
	}
	if value.Record != nil {
		for _, field := range value.Record.Fields {
			if typeNeedsTextSupport(field.Type) {
				return true
			}
		}
	}
	if value.Optional != nil {
		return typeNeedsTextSupport(value.Optional.Value)
	}
	if value.List != nil {
		return typeNeedsTextSupport(value.List.Element)
	}
	if value.Result != nil {
		return typeNeedsTextSupport(value.Result.Success) || typeNeedsTextSupport(value.Result.Failure)
	}
	return false
}

func programNeedsOptionalSupport(functions []coreir.Function) bool {
	for _, function := range functions {
		if function.ReturnType.Kind == coreir.TypeOptional || expressionNeedsOptionalSupport(function.Body) {
			return true
		}
		for _, parameter := range function.Parameters {
			if parameter.Type.Kind == coreir.TypeOptional {
				return true
			}
		}
	}
	return false
}

func programNeedsListSupport(functions []coreir.Function) bool {
	for _, function := range functions {
		if typeContainsList(function.ReturnType) || typeContainsList(function.Body.Type) {
			return true
		}
		for _, parameter := range function.Parameters {
			if typeContainsList(parameter.Type) {
				return true
			}
		}
	}
	return false
}

func typeContainsList(value coreir.Type) bool {
	if value.Kind == coreir.TypeList {
		return true
	}
	if value.Result != nil {
		return typeContainsList(value.Result.Success) || typeContainsList(value.Result.Failure)
	}
	return false
}

func programNeedsListCount(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsListCount(function.Body) {
			return true
		}
	}
	return false
}

func programNeedsListAppend(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsListAppend(function.Body) {
			return true
		}
	}
	return false
}

func programNeedsListAt(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsListAt(function.Body) {
			return true
		}
	}
	return false
}

func programNeedsListFindByText(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsListFindByText(function.Body) {
			return true
		}
	}
	return false
}

func programNeedsListFilterByText(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsListFilterByText(function.Body) {
			return true
		}
	}
	return false
}

func programNeedsListFilterContainsCaseFolded(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsListFilterContainsCaseFolded(function.Body) {
			return true
		}
	}
	return false
}

func expressionNeedsListFilterContainsCaseFolded(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprListFilterContainsCaseFolded:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsListFilterContainsCaseFolded(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsListFilterContainsCaseFolded(*expression.Binary.Left) || expressionNeedsListFilterContainsCaseFolded(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsListFilterContainsCaseFolded(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsListFilterContainsCaseFolded(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func expressionNeedsListFilterByText(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprListFilterByText:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsListFilterByText(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsListFilterByText(*expression.Binary.Left) || expressionNeedsListFilterByText(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsListFilterByText(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsListFilterByText(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func expressionNeedsListFindByText(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprListFindByText:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsListFindByText(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsListFindByText(*expression.Binary.Left) || expressionNeedsListFindByText(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsListFindByText(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsListFindByText(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func expressionNeedsListAt(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprListAt:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsListAt(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsListAt(*expression.Binary.Left) || expressionNeedsListAt(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsListAt(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsListAt(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func expressionNeedsListAppend(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprListAppend:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsListAppend(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsListAppend(*expression.Binary.Left) || expressionNeedsListAppend(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsListAppend(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsListAppend(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func expressionNeedsListCount(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprListCount:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsListCount(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsListCount(*expression.Binary.Left) || expressionNeedsListCount(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsListCount(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsListCount(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func expressionNeedsOptionalSupport(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprOptionalSome, coreir.ExprOptionalNone, coreir.ExprOptionalHasValue, coreir.ExprOptionalValueOr, coreir.ExprListAt, coreir.ExprListFindByText:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsOptionalSupport(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsOptionalSupport(*expression.Binary.Left) || expressionNeedsOptionalSupport(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsOptionalSupport(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsOptionalSupport(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func programNeedsOptionalDefault(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsOptionalDefault(function.Body) {
			return true
		}
	}
	return false
}

func programNeedsRecordOptionalSupport(functions []coreir.Function) bool {
	for _, function := range functions {
		if typeContainsRecordOptional(function.ReturnType) || expressionContainsRecordOptional(function.Body) {
			return true
		}
		for _, parameter := range function.Parameters {
			if typeContainsRecordOptional(parameter.Type) {
				return true
			}
		}
	}
	return false
}

func typeContainsRecordOptional(value coreir.Type) bool {
	return value.Kind == coreir.TypeOptional && value.Optional != nil && value.Optional.Value.Kind == coreir.TypeRecord
}

func expressionContainsRecordOptional(expression coreir.Expr) bool {
	if typeContainsRecordOptional(expression.Type) {
		return true
	}
	switch expression.Kind {
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionContainsRecordOptional(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionContainsRecordOptional(*expression.Binary.Left) || expressionContainsRecordOptional(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionContainsRecordOptional(*expression.Field.Receiver)
	case coreir.ExprOptionalSome:
		return expression.Some != nil && expression.Some.Value != nil && expressionContainsRecordOptional(*expression.Some.Value)
	case coreir.ExprOptionalHasValue:
		return expression.HasValue != nil && expression.HasValue.Value != nil && expressionContainsRecordOptional(*expression.HasValue.Value)
	case coreir.ExprOptionalValueOr:
		return expression.ValueOr != nil && expression.ValueOr.Value != nil && expression.ValueOr.Fallback != nil && (expressionContainsRecordOptional(*expression.ValueOr.Value) || expressionContainsRecordOptional(*expression.ValueOr.Fallback))
	}
	return false
}

func expressionNeedsOptionalDefault(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprOptionalValueOr:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsOptionalDefault(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsOptionalDefault(*expression.Binary.Left) || expressionNeedsOptionalDefault(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsOptionalDefault(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsOptionalDefault(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func emitOptionalSupport(out *strings.Builder, validateText, emitValueOr, validateRecordPayloads bool, optionalTypeName string, records []coreir.Type) {
	fmt.Fprintf(out, "type %s[T any] interface {\n\tpipelangOptional(T)\n}\n\n", optionalTypeName)
	out.WriteString("type pipelangOptionalSome[T any] struct {\n\tvalue T\n}\n\n")
	out.WriteString("func (pipelangOptionalSome[T]) pipelangOptional(T) {}\n\n")
	out.WriteString("type pipelangOptionalNone[T any] struct{}\n\n")
	out.WriteString("func (pipelangOptionalNone[T]) pipelangOptional(T) {}\n\n")
	if validateRecordPayloads {
		out.WriteString("func pipelangValidateOptionalPayload[T any](value T) {\n\tswitch typed := any(value).(type) {\n")
		if validateText {
			out.WriteString("\tcase string:\n\t\tpipelangValidateText(typed)\n")
		}
		out.WriteString("\tcase int64, float64, bool:\n\t\t_ = typed\n")
		for _, record := range records {
			fmt.Fprintf(out, "\tcase %s:\n\t\t%s(typed)\n", recordGoTypeName(record), recordValidationName(record))
		}
		out.WriteString("\tdefault:\n\t\tpanic(\"invalid PipeLang Optional payload\")\n\t}\n}\n\n")
	}
	fmt.Fprintf(out, "func pipelangSomeValue[T any](value T) %s[T] {\n\tresult := %s[T](pipelangOptionalSome[T]{value: value})\n\tpipelangValidateOptional(result)\n\treturn result\n}\n\n", optionalTypeName, optionalTypeName)
	fmt.Fprintf(out, "func pipelangNoneValue[T any]() %s[T] {\n\treturn pipelangOptionalNone[T]{}\n}\n\n", optionalTypeName)
	fmt.Fprintf(out, "func pipelangValidateOptional[T any](value %s[T]) {\n\tswitch typed := value.(type) {\n\tcase pipelangOptionalSome[T]:\n", optionalTypeName)
	if validateRecordPayloads {
		out.WriteString("\t\tpipelangValidateOptionalPayload(typed.value)\n")
	} else if validateText {
		out.WriteString("\t\tif text, ok := any(typed.value).(string); ok {\n\t\t\tpipelangValidateText(text)\n\t\t}\n")
	} else {
		out.WriteString("\t\t_ = typed\n")
	}
	out.WriteString("\tcase pipelangOptionalNone[T]:\n\tdefault:\n\t\tpanic(\"invalid PipeLang Optional value\")\n\t}\n}\n\n")
	fmt.Fprintf(out, "func pipelangHasValue[T any](value %s[T]) bool {\n\tpipelangValidateOptional(value)\n\t_, present := value.(pipelangOptionalSome[T])\n\treturn present\n}\n\n", optionalTypeName)
	if !emitValueOr {
		return
	}
	fmt.Fprintf(out, "func pipelangValueOr[T any](value %s[T], fallback T) T {\n\tpipelangValidateOptional(value)\n", optionalTypeName)
	if validateRecordPayloads {
		out.WriteString("\tpipelangValidateOptionalPayload(fallback)\n")
	} else if validateText {
		out.WriteString("\tif text, ok := any(fallback).(string); ok {\n\t\tpipelangValidateText(text)\n\t}\n")
	}
	out.WriteString("\tswitch typed := value.(type) {\n\tcase pipelangOptionalSome[T]:\n\t\treturn typed.value\n\tcase pipelangOptionalNone[T]:\n\t\treturn fallback\n\tdefault:\n\t\tpanic(\"invalid PipeLang Optional value\")\n\t}\n}\n\n")
}

func optionalGoTypeName(functions []coreir.Function) string {
	used := make(map[string]struct{}, len(functions))
	for _, function := range functions {
		used[FunctionName(function)] = struct{}{}
	}
	const base = "PipeLangOptional"
	if _, collision := used[base]; !collision {
		return base
	}
	for suffix := 1; ; suffix++ {
		candidate := base + "Value"
		if suffix > 1 {
			candidate += strconv.Itoa(suffix)
		}
		if _, collision := used[candidate]; !collision {
			return candidate
		}
	}
}

func collectRecordTypes(functions []coreir.Function) ([]coreir.Type, error) {
	byIdentity := map[string]coreir.Type{}
	identityByGoName := map[string]string{}
	var collect func(coreir.Type) error
	collect = func(value coreir.Type) error {
		if value.Kind == coreir.TypeResult && value.Result != nil {
			if err := collect(value.Result.Success); err != nil {
				return err
			}
			return collect(value.Result.Failure)
		}
		if value.Kind == coreir.TypeList && value.List != nil {
			return collect(value.List.Element)
		}
		if value.Kind == coreir.TypeOptional && value.Optional != nil {
			return collect(value.Optional.Value)
		}
		if value.Kind != coreir.TypeRecord {
			return nil
		}
		if value.Identity == nil || value.Record == nil {
			return fmt.Errorf("record type is missing identity or schema")
		}
		key := value.Identity.PackageID + "\x00" + value.Identity.Path
		if previous, exists := byIdentity[key]; exists && !coreir.TypeEqual(previous, value) {
			return fmt.Errorf("record identity %q has conflicting schemas", value.Identity.Path)
		}
		byIdentity[key] = value
		goName := recordGoTypeName(value)
		if previous, exists := identityByGoName[goName]; exists && previous != key {
			return fmt.Errorf("record identities collide on generated Go name %q", goName)
		}
		identityByGoName[goName] = key
		for _, field := range value.Record.Fields {
			if err := collect(field.Type); err != nil {
				return err
			}
		}
		return nil
	}
	for _, function := range functions {
		if err := collect(function.ReturnType); err != nil {
			return nil, err
		}
		for _, parameter := range function.Parameters {
			if err := collect(parameter.Type); err != nil {
				return nil, err
			}
		}
	}
	keys := make([]string, 0, len(byIdentity))
	for key := range byIdentity {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	records := make([]coreir.Type, 0, len(keys))
	for _, key := range keys {
		records = append(records, byIdentity[key])
	}
	return records, nil
}

func collectListTypes(functions []coreir.Function) ([]coreir.Type, error) {
	byElement := map[string]coreir.Type{}
	var collect func(coreir.Type) error
	collect = func(value coreir.Type) error {
		if value.Kind == coreir.TypeResult && value.Result != nil {
			if err := collect(value.Result.Success); err != nil {
				return err
			}
			return collect(value.Result.Failure)
		}
		if value.Kind != coreir.TypeList {
			return nil
		}
		if value.List == nil || value.List.Element.Identity == nil {
			return fmt.Errorf("list type is missing its record element identity")
		}
		key := value.List.Element.Identity.PackageID + "\x00" + value.List.Element.Identity.Path
		if previous, exists := byElement[key]; exists && !coreir.TypeEqual(previous, value) {
			return fmt.Errorf("record-list element identity %q has conflicting schemas", value.List.Element.Identity.Path)
		}
		byElement[key] = value
		return nil
	}
	for _, function := range functions {
		if err := collect(function.ReturnType); err != nil {
			return nil, err
		}
		for _, parameter := range function.Parameters {
			if err := collect(parameter.Type); err != nil {
				return nil, err
			}
		}
	}
	keys := make([]string, 0, len(byElement))
	for key := range byElement {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	result := make([]coreir.Type, 0, len(keys))
	for _, key := range keys {
		result = append(result, byElement[key])
	}
	return result, nil
}

func emitListSupport(out *strings.Builder, list coreir.Type, emitAppend, emitAt bool, findByText []coreir.ListFindByText, filterByText []coreir.ListFilterByText, filterContainsCaseFolded []coreir.ListFilterContainsCaseFolded, optionalTypeName string) {
	element := list.List.Element
	elementType := recordGoTypeName(element)
	validation := listValidationName(list)
	fmt.Fprintf(out, "func %s(values []%s) {\n", validation, elementType)
	out.WriteString("\tif values == nil {\n\t\tpanic(\"invalid PipeLang List value\")\n\t}\n")
	fmt.Fprintf(out, "\tfor _, value := range values {\n\t\t%s(value)\n\t}\n", recordValidationName(element))
	out.WriteString("}\n\n")
	fmt.Fprintf(out, "func %s(values []%s) []%s {\n\t%s(values)\n\tresult := make([]%s, len(values))\n\tcopy(result, values)\n\treturn result\n}\n\n", listCloneName(list), elementType, elementType, validation, elementType)
	fmt.Fprintf(out, "func %s() []%s {\n\treturn make([]%s, 0)\n}\n\n", listEmptyName(list), elementType, elementType)
	fmt.Fprintf(out, "func %s(value %s) []%s {\n\t%s(value)\n\treturn []%s{value}\n}\n\n", listSingletonName(list), elementType, elementType, recordValidationName(element), elementType)
	if emitAppend {
		fmt.Fprintf(out, "func %s(values []%s, value %s) []%s {\n\t%s(values)\n\t%s(value)\n\tif uint64(len(values)) == uint64(^uint64(0)>>1) {\n\t\tpanic(\"PipeLang List cardinality exceeds signed 64-bit range\")\n\t}\n\tresult := make([]%s, len(values)+1)\n\tcopy(result, values)\n\tresult[len(values)] = value\n\treturn result\n}\n\n", listAppendName(list), elementType, elementType, elementType, validation, recordValidationName(element), elementType)
	}
	if emitAt {
		fmt.Fprintf(out, "func %s(values []%s, index int64) %s[%s] {\n\t%s(values)\n\tif index < 0 || uint64(index) >= uint64(len(values)) {\n\t\treturn pipelangNoneValue[%s]()\n\t}\n\treturn pipelangSomeValue(values[index])\n}\n\n", listAtName(list), elementType, optionalTypeName, elementType, validation, elementType)
	}
	fieldNames := recordGoFieldNames(element)
	for _, selector := range findByText {
		fmt.Fprintf(out, "func %s(values []%s, key string) %s[%s] {\n\t%s(values)\n\tpipelangValidateText(key)\n\tfor _, value := range values {\n\t\tif pipelangCompareOrdinalText(value.%s, key) == 0 {\n\t\t\treturn pipelangSomeValue(value)\n\t\t}\n\t}\n\treturn pipelangNoneValue[%s]()\n}\n\n", listFindByTextName(list, selector), elementType, optionalTypeName, elementType, validation, fieldNames[selector.Position], elementType)
	}
	for _, selector := range filterByText {
		fmt.Fprintf(out, "func %s(values []%s, key string) []%s {\n\t%s(values)\n\tpipelangValidateText(key)\n\tresult := make([]%s, 0, len(values))\n\tfor _, value := range values {\n\t\tif pipelangCompareOrdinalText(value.%s, key) == 0 {\n\t\t\tresult = append(result, value)\n\t\t}\n\t}\n\treturn result\n}\n\n", listFilterByTextName(list, selector), elementType, elementType, validation, elementType, fieldNames[selector.Position])
	}
	for _, selector := range filterContainsCaseFolded {
		fmt.Fprintf(out, "func %s(values []%s, query string) []%s {\n\t%s(values)\n\tpipelangValidateText(query)\n\tresult := make([]%s, 0, len(values))\n\tfor _, value := range values {\n\t\tif pipelangContainsCaseFoldedText(value.%s, query) {\n\t\t\tresult = append(result, value)\n\t\t}\n\t}\n\treturn result\n}\n\n", listFilterContainsCaseFoldedName(list, selector), elementType, elementType, validation, elementType, fieldNames[selector.Position])
	}
}

func programAppendsList(functions []coreir.Function, list coreir.Type) bool {
	for _, function := range functions {
		if expressionAppendsList(function.Body, list) {
			return true
		}
	}
	return false
}

func expressionAppendsList(expression coreir.Expr, list coreir.Type) bool {
	switch expression.Kind {
	case coreir.ExprListAppend:
		return coreir.TypeEqual(expression.Type, list)
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionAppendsList(*expression.Unary.Operand, list)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionAppendsList(*expression.Binary.Left, list) || expressionAppendsList(*expression.Binary.Right, list))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionAppendsList(*expression.Field.Receiver, list)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionAppendsList(*field.Value, list) {
					return true
				}
			}
		}
	}
	return false
}

func programIndexesList(functions []coreir.Function, list coreir.Type) bool {
	for _, function := range functions {
		if expressionIndexesList(function.Body, list) {
			return true
		}
	}
	return false
}

func expressionIndexesList(expression coreir.Expr, list coreir.Type) bool {
	switch expression.Kind {
	case coreir.ExprListAt:
		return expression.ListAt != nil && expression.ListAt.Values != nil && coreir.TypeEqual(expression.ListAt.Values.Type, list)
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionIndexesList(*expression.Unary.Operand, list)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionIndexesList(*expression.Binary.Left, list) || expressionIndexesList(*expression.Binary.Right, list))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionIndexesList(*expression.Field.Receiver, list)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionIndexesList(*field.Value, list) {
					return true
				}
			}
		}
	}
	return false
}

func programFindsListByText(functions []coreir.Function, list coreir.Type) []coreir.ListFindByText {
	byPosition := map[int]coreir.ListFindByText{}
	for _, function := range functions {
		expression := function.Body
		if expression.Kind != coreir.ExprListFindByText || expression.ListFind == nil || expression.ListFind.Values == nil || !coreir.TypeEqual(expression.ListFind.Values.Type, list) {
			continue
		}
		byPosition[expression.ListFind.Position] = *expression.ListFind
	}
	positions := make([]int, 0, len(byPosition))
	for position := range byPosition {
		positions = append(positions, position)
	}
	sort.Ints(positions)
	result := make([]coreir.ListFindByText, 0, len(positions))
	for _, position := range positions {
		result = append(result, byPosition[position])
	}
	return result
}

func programFiltersListByText(functions []coreir.Function, list coreir.Type) []coreir.ListFilterByText {
	byPosition := map[int]coreir.ListFilterByText{}
	for _, function := range functions {
		expression := function.Body
		if expression.Kind != coreir.ExprListFilterByText || expression.ListFilter == nil || expression.ListFilter.Values == nil || !coreir.TypeEqual(expression.ListFilter.Values.Type, list) {
			continue
		}
		byPosition[expression.ListFilter.Position] = *expression.ListFilter
	}
	positions := make([]int, 0, len(byPosition))
	for position := range byPosition {
		positions = append(positions, position)
	}
	sort.Ints(positions)
	result := make([]coreir.ListFilterByText, 0, len(positions))
	for _, position := range positions {
		result = append(result, byPosition[position])
	}
	return result
}

func programFiltersListContainsCaseFolded(functions []coreir.Function, list coreir.Type) []coreir.ListFilterContainsCaseFolded {
	byPosition := map[int]coreir.ListFilterContainsCaseFolded{}
	for _, function := range functions {
		expression := function.Body
		filter := expression.ListFilterContainsCaseFolded
		if expression.Kind != coreir.ExprListFilterContainsCaseFolded || filter == nil || filter.Values == nil || !coreir.TypeEqual(filter.Values.Type, list) {
			continue
		}
		byPosition[filter.Position] = *filter
	}
	positions := make([]int, 0, len(byPosition))
	for position := range byPosition {
		positions = append(positions, position)
	}
	sort.Ints(positions)
	result := make([]coreir.ListFilterContainsCaseFolded, 0, len(positions))
	for _, position := range positions {
		result = append(result, byPosition[position])
	}
	return result
}

func listHelperSuffix(list coreir.Type) string {
	return strings.TrimPrefix(recordGoTypeName(list.List.Element), "PipeLangRecord")
}

func listValidationName(list coreir.Type) string {
	return "pipelangValidateList" + listHelperSuffix(list)
}
func listCloneName(list coreir.Type) string { return "pipelangCloneList" + listHelperSuffix(list) }
func listEmptyName(list coreir.Type) string { return "pipelangEmptyList" + listHelperSuffix(list) }
func listSingletonName(list coreir.Type) string {
	return "pipelangSingletonList" + listHelperSuffix(list)
}
func listAppendName(list coreir.Type) string { return "pipelangAppendList" + listHelperSuffix(list) }
func listAtName(list coreir.Type) string     { return "pipelangAtList" + listHelperSuffix(list) }
func listFindByTextName(list coreir.Type, selector coreir.ListFindByText) string {
	return "pipelangFindByTextList" + listHelperSuffix(list) + "Field" + strconv.Itoa(selector.Position)
}
func listFilterByTextName(list coreir.Type, selector coreir.ListFilterByText) string {
	return "pipelangFilterByTextList" + listHelperSuffix(list) + "Field" + strconv.Itoa(selector.Position)
}
func listFilterContainsCaseFoldedName(list coreir.Type, selector coreir.ListFilterContainsCaseFolded) string {
	return "pipelangFilterContainsCaseFoldedList" + listHelperSuffix(list) + "Field" + strconv.Itoa(selector.Position)
}

func isSnapshotResultType(value coreir.Type) bool {
	return value.Kind == coreir.TypeResult && value.Result != nil && value.Result.Success.Kind == coreir.TypeList && value.Result.Success.List != nil && value.Result.Success.List.Element.Kind == coreir.TypeRecord && isTextType(value.Result.Failure)
}

func programNeedsSnapshotResult(functions []coreir.Function) bool {
	for _, function := range functions {
		if isSnapshotResultType(function.ReturnType) || isSnapshotResultType(function.Body.Type) {
			return true
		}
		for _, parameter := range function.Parameters {
			if isSnapshotResultType(parameter.Type) {
				return true
			}
		}
	}
	return false
}

func collectSnapshotResultTypes(functions []coreir.Function) ([]coreir.Type, error) {
	byIdentity := map[string]coreir.Type{}
	collect := func(value coreir.Type) error {
		if !isSnapshotResultType(value) {
			return nil
		}
		identity := value.Result.Success.List.Element.Identity
		if identity == nil || identity.PackageID == "" || identity.Path == "" {
			return fmt.Errorf("snapshot Result is missing its record element identity")
		}
		key := identity.PackageID + "\x00" + identity.Path
		if previous, exists := byIdentity[key]; exists && !coreir.TypeEqual(previous, value) {
			return fmt.Errorf("snapshot Result element identity %q has conflicting schemas", identity.Path)
		}
		byIdentity[key] = value
		return nil
	}
	for _, function := range functions {
		if err := collect(function.ReturnType); err != nil {
			return nil, err
		}
		if err := collect(function.Body.Type); err != nil {
			return nil, err
		}
		for _, parameter := range function.Parameters {
			if err := collect(parameter.Type); err != nil {
				return nil, err
			}
		}
	}
	keys := make([]string, 0, len(byIdentity))
	for key := range byIdentity {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	results := make([]coreir.Type, 0, len(keys))
	for _, key := range keys {
		results = append(results, byIdentity[key])
	}
	return results, nil
}

func emitSnapshotResultType(out *strings.Builder) {
	out.WriteString("type PipeLangResult[S, E any] struct {\n\tOK bool\n\tValue S\n\tError E\n}\n\n")
}

func snapshotResultSuffix(result coreir.Type) string {
	return listHelperSuffix(result.Result.Success)
}

func snapshotResultValidationName(result coreir.Type) string {
	return "pipelangValidateSnapshotResult" + snapshotResultSuffix(result)
}

func snapshotResultCloneName(result coreir.Type) string {
	return "pipelangCloneSnapshotResult" + snapshotResultSuffix(result)
}

func snapshotResultOKName(result coreir.Type) string {
	return "pipelangSnapshotResultOK" + snapshotResultSuffix(result)
}

func snapshotResultErrName(result coreir.Type) string {
	return "pipelangSnapshotResultErr" + snapshotResultSuffix(result)
}

func snapshotResultIsOKName(result coreir.Type) string {
	return "pipelangSnapshotResultIsOK" + snapshotResultSuffix(result)
}

func snapshotResultSuccessOrName(result coreir.Type) string {
	return "pipelangSnapshotResultSuccessOr" + snapshotResultSuffix(result)
}

func snapshotResultFailureOrName(result coreir.Type) string {
	return "pipelangSnapshotResultFailureOr" + snapshotResultSuffix(result)
}

func emitSnapshotResultSupport(out *strings.Builder, result coreir.Type) {
	list := result.Result.Success
	elementType := recordGoTypeName(list.List.Element)
	resultType := fmt.Sprintf("PipeLangResult[[]%s, string]", elementType)
	validate := snapshotResultValidationName(result)
	fmt.Fprintf(out, "func %s(value %s) {\n", validate, resultType)
	out.WriteString("\tif value.OK {\n")
	fmt.Fprintf(out, "\t\t%s(value.Value)\n", listValidationName(list))
	out.WriteString("\t\tif value.Error != \"\" {\n\t\t\tpanic(\"invalid PipeLang snapshot Result value\")\n\t\t}\n\t\treturn\n\t}\n")
	out.WriteString("\tif value.Value != nil {\n\t\tpanic(\"invalid PipeLang snapshot Result value\")\n\t}\n\tpipelangValidateText(value.Error)\n}\n\n")
	fmt.Fprintf(out, "func %s(value %s) %s {\n\t%s(value)\n\tif value.OK {\n\t\tvalue.Value = %s(value.Value)\n\t}\n\treturn value\n}\n\n", snapshotResultCloneName(result), resultType, resultType, validate, listCloneName(list))
	fmt.Fprintf(out, "func %s(value []%s) %s {\n\treturn %s{OK: true, Value: %s(value)}\n}\n\n", snapshotResultOKName(result), elementType, resultType, resultType, listCloneName(list))
	fmt.Fprintf(out, "func %s(failure string) %s {\n\tpipelangValidateText(failure)\n\treturn %s{Error: failure}\n}\n\n", snapshotResultErrName(result), resultType, resultType)
	fmt.Fprintf(out, "func %s(value %s) bool {\n\t%s(value)\n\treturn value.OK\n}\n\n", snapshotResultIsOKName(result), resultType, validate)
	fmt.Fprintf(out, "func %s(value %s, fallback []%s) []%s {\n\t%s(value)\n\t%s(fallback)\n\tif value.OK {\n\t\treturn %s(value.Value)\n\t}\n\treturn %s(fallback)\n}\n\n", snapshotResultSuccessOrName(result), resultType, elementType, elementType, validate, listValidationName(list), listCloneName(list), listCloneName(list))
	fmt.Fprintf(out, "func %s(value %s, fallback string) string {\n\t%s(value)\n\tpipelangValidateText(fallback)\n\tif value.OK {\n\t\treturn fallback\n\t}\n\treturn value.Error\n}\n\n", snapshotResultFailureOrName(result), resultType, validate)
}

func emitRecordType(out *strings.Builder, record coreir.Type, emitConstructor bool, optionalTypeName string) {
	typeName := recordGoTypeName(record)
	fieldNames := recordGoFieldNames(record)
	fmt.Fprintf(out, "type %s struct {\n", typeName)
	for index, field := range record.Record.Fields {
		fieldType, _ := goType(field.Type, optionalTypeName)
		fmt.Fprintf(out, "\t%s %s\n", fieldNames[index], fieldType)
	}
	out.WriteString("}\n\n")
	fmt.Fprintf(out, "func %s(value %s) {\n", recordValidationName(record), typeName)
	for index, field := range record.Record.Fields {
		if isTextType(field.Type) {
			fmt.Fprintf(out, "\tpipelangValidateText(value.%s)\n", fieldNames[index])
		}
	}
	out.WriteString("}\n\n")
	if !emitConstructor {
		return
	}
	fmt.Fprintf(out, "func %s(", recordConstructionName(record))
	for index, field := range record.Record.Fields {
		if index > 0 {
			out.WriteString(", ")
		}
		fieldType, _ := goType(field.Type, optionalTypeName)
		fmt.Fprintf(out, "field%d %s", index, fieldType)
	}
	fmt.Fprintf(out, ") %s {\n", typeName)
	fmt.Fprintf(out, "\tvalue := %s{\n", typeName)
	for index, fieldName := range fieldNames {
		fmt.Fprintf(out, "\t\t%s: field%d,\n", fieldName, index)
	}
	out.WriteString("\t}\n")
	fmt.Fprintf(out, "\t%s(value)\n", recordValidationName(record))
	out.WriteString("\treturn value\n")
	out.WriteString("}\n\n")
}

func programConstructsRecord(functions []coreir.Function, record coreir.Type) bool {
	for _, function := range functions {
		if expressionConstructsRecord(function.Body, record) {
			return true
		}
	}
	return false
}

func expressionConstructsRecord(expression coreir.Expr, record coreir.Type) bool {
	switch expression.Kind {
	case coreir.ExprRecordConstruct:
		if coreir.TypeEqual(expression.Type, record) {
			return true
		}
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionConstructsRecord(*field.Value, record) {
					return true
				}
			}
		}
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionConstructsRecord(*expression.Unary.Operand, record)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionConstructsRecord(*expression.Binary.Left, record) || expressionConstructsRecord(*expression.Binary.Right, record))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionConstructsRecord(*expression.Field.Receiver, record)
	}
	return false
}

func recordGoTypeName(record coreir.Type) string {
	if record.Identity == nil {
		return "PipeLangRecordInvalid"
	}
	return "PipeLangRecord" + exportedIdentifier(record.Identity.PackageID+"_"+record.Identity.Path)
}

func recordValidationName(record coreir.Type) string {
	return "pipelangValidate" + strings.TrimPrefix(recordGoTypeName(record), "PipeLang")
}

func recordConstructionName(record coreir.Type) string {
	return "pipelangNew" + strings.TrimPrefix(recordGoTypeName(record), "PipeLang")
}

func recordGoFieldNames(record coreir.Type) []string {
	result := make([]string, len(record.Record.Fields))
	used := map[string]struct{}{}
	for index, field := range record.Record.Fields {
		base := exportedIdentifier(field.Name)
		candidate := base
		for suffix := 2; ; suffix++ {
			if _, exists := used[candidate]; !exists {
				break
			}
			candidate = base + strconv.Itoa(suffix)
		}
		used[candidate] = struct{}{}
		result[index] = candidate
	}
	return result
}

func expressionNeedsTextSupport(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprTextContainsCaseFolded:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsTextSupport(*expression.Unary.Operand)
	case coreir.ExprBinary:
		if expression.Binary == nil || expression.Binary.Left == nil || expression.Binary.Right == nil {
			return false
		}
		if isTextType(expression.Binary.Left.Type) && isTextType(expression.Binary.Right.Type) {
			return true
		}
		return expressionNeedsTextSupport(*expression.Binary.Left) || expressionNeedsTextSupport(*expression.Binary.Right)
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsTextSupport(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record == nil {
			return false
		}
		for _, field := range expression.Record.Fields {
			if field.Value != nil && expressionNeedsTextSupport(*field.Value) {
				return true
			}
		}
		return false
	case coreir.ExprListSingleton:
		return expression.ListOne != nil && expression.ListOne.Value != nil && expressionNeedsTextSupport(*expression.ListOne.Value)
	case coreir.ExprListCount:
		return expression.ListCount != nil && expression.ListCount.Value != nil && expressionNeedsTextSupport(*expression.ListCount.Value)
	case coreir.ExprListAppend:
		return expression.ListAppend != nil && expression.ListAppend.Values != nil && expression.ListAppend.Value != nil && (expressionNeedsTextSupport(*expression.ListAppend.Values) || expressionNeedsTextSupport(*expression.ListAppend.Value))
	case coreir.ExprListFindByText:
		return true
	case coreir.ExprListFilterByText:
		return true
	case coreir.ExprListFilterContainsCaseFolded:
		return true
	case coreir.ExprResultOK:
		return expression.ResultOK != nil && expression.ResultOK.Value != nil && expressionNeedsTextSupport(*expression.ResultOK.Value)
	case coreir.ExprResultErr:
		return true
	case coreir.ExprResultIsOK:
		return expression.ResultIsOK != nil && expression.ResultIsOK.Value != nil && expressionNeedsTextSupport(*expression.ResultIsOK.Value)
	case coreir.ExprResultSuccessOr:
		return expression.SuccessOr != nil && expression.SuccessOr.Value != nil && expression.SuccessOr.Fallback != nil && (expressionNeedsTextSupport(*expression.SuccessOr.Value) || expressionNeedsTextSupport(*expression.SuccessOr.Fallback))
	case coreir.ExprResultFailureOr:
		return true
	default:
		return false
	}
}

func programNeedsCaseFoldedText(functions []coreir.Function) bool {
	for _, function := range functions {
		if expressionNeedsCaseFoldedText(function.Body) {
			return true
		}
	}
	return false
}

func expressionNeedsCaseFoldedText(expression coreir.Expr) bool {
	switch expression.Kind {
	case coreir.ExprTextContainsCaseFolded, coreir.ExprListFilterContainsCaseFolded:
		return true
	case coreir.ExprUnary:
		return expression.Unary != nil && expression.Unary.Operand != nil && expressionNeedsCaseFoldedText(*expression.Unary.Operand)
	case coreir.ExprBinary:
		return expression.Binary != nil && expression.Binary.Left != nil && expression.Binary.Right != nil && (expressionNeedsCaseFoldedText(*expression.Binary.Left) || expressionNeedsCaseFoldedText(*expression.Binary.Right))
	case coreir.ExprFieldProjection:
		return expression.Field != nil && expression.Field.Receiver != nil && expressionNeedsCaseFoldedText(*expression.Field.Receiver)
	case coreir.ExprRecordConstruct:
		if expression.Record != nil {
			for _, field := range expression.Record.Fields {
				if field.Value != nil && expressionNeedsCaseFoldedText(*field.Value) {
					return true
				}
			}
		}
	}
	return false
}

func emitTextSupport(out *strings.Builder, emitCaseFold bool) {
	out.WriteString(`func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

`)
	if !emitCaseFold {
		return
	}

	out.WriteString("var pipelangCaseFolding17 = map[rune]string{\n")
	for _, mapping := range coreir.CaseFoldingMappings() {
		fmt.Fprintf(out, "\t0x%X: %q,\n", mapping.Source, mapping.Replacement)
	}
	out.WriteString(`}

func pipelangFoldValidCaseText(value string) string {
	var folded strings.Builder
	folded.Grow(len(value))
	for _, scalar := range value {
		if replacement, ok := pipelangCaseFolding17[scalar]; ok {
			folded.WriteString(replacement)
		} else {
			folded.WriteRune(scalar)
		}
	}
	return folded.String()
}

func pipelangContainsCaseFoldedText(value, query string) bool {
	pipelangValidateText(value)
	pipelangValidateText(query)
	return strings.Contains(pipelangFoldValidCaseText(value), pipelangFoldValidCaseText(query))
}

`)
}

func programNeedsArithmeticResult(functions []coreir.Function) bool {
	for _, function := range functions {
		if function.ReturnType.Kind == coreir.TypeResult && function.ReturnType.Result != nil && function.ReturnType.Result.Failure.Kind == coreir.TypeArithmeticError {
			return true
		}
	}
	return false
}

func arithmeticHelperName(operator coreir.Operator) (string, bool) {
	switch operator {
	case coreir.OperatorAdd:
		return "pipelangCheckedAddInt64", true
	case coreir.OperatorSubtract:
		return "pipelangCheckedSubtractInt64", true
	case coreir.OperatorMultiply:
		return "pipelangCheckedMultiplyInt64", true
	case coreir.OperatorDivide:
		return "pipelangCheckedDivideBinary64", true
	default:
		return "", false
	}
}

func emitArithmeticSupport(out *strings.Builder) {
	out.WriteString(`type PipeLangArithmeticError string

const (
	PipeLangArithmeticOverflow PipeLangArithmeticError = "overflow"
	PipeLangArithmeticDivisionByZero PipeLangArithmeticError = "division_by_zero"
)

type PipeLangArithmeticResult[T any] struct {
	OK bool
	Value T
	Error PipeLangArithmeticError
}

func pipelangCheckedAddInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if (right > 0 && left > maximum-right) || (right < 0 && left < minimum-right) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: left + right}
}

func pipelangCheckedSubtractInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if (right < 0 && left > maximum+right) || (right > 0 && left < minimum+right) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: left - right}
}

func pipelangCheckedMultiplyInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if left == 0 || right == 0 {
		return PipeLangArithmeticResult[int64]{OK: true}
	}
	if (left == minimum && right == -1) || (right == minimum && left == -1) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	value := left * right
	if value/right != left {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: value}
}

func pipelangCheckedNegateInt64(value int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if value == minimum {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: -value}
}

func pipelangCheckedDivideBinary64(left, right float64) PipeLangArithmeticResult[float64] {
	if right == 0 {
		return PipeLangArithmeticResult[float64]{Error: PipeLangArithmeticDivisionByZero}
	}
	return PipeLangArithmeticResult[float64]{OK: true, Value: left / right}
}

`)
}

func backendError(function coreir.Function, code, message string) error {
	return &Error{Code: code, Function: identityKey(function.Identity), Message: message}
}

func identityKey(identity coreir.SemanticIdentity) string {
	return identity.PackageID + ":" + identity.Path
}

func finalPathSegment(path string) string {
	if index := strings.LastIndexByte(path, '.'); index >= 0 {
		return path[index+1:]
	}
	return path
}

func exportedIdentifier(value string) string {
	var out strings.Builder
	upperNext := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if out.Len() == 0 && unicode.IsDigit(r) {
			out.WriteRune('X')
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		}
		out.WriteRune(r)
	}
	if out.Len() == 0 {
		return "Function"
	}
	return out.String()
}
