if(NOT OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(RELEASE_VERSION)
    if(NOT RELEASE_VERSION MATCHES "^[A-Za-z0-9.+_-]+$")
        message(FATAL_ERROR "Release version contains unsupported characters")
    endif()
    set(version "${RELEASE_VERSION}")
else()
    set(version "dev+unknown")
    find_package(Git QUIET)
    if(GIT_FOUND AND SOURCE_DIR)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
            OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE revision_result ERROR_QUIET)
        if(revision_result EQUAL 0 AND revision MATCHES "^[0-9a-f]+$")
            set(version "dev+${revision}")
            execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=normal
                OUTPUT_VARIABLE changes RESULT_VARIABLE status_result ERROR_QUIET)
            if(NOT status_result EQUAL 0)
                string(APPEND version ".state-unknown")
            elseif(NOT changes STREQUAL "")
                string(APPEND version ".dirty")
            endif()
        endif()
    endif()
endif()

get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
set(content "// Generated build identity. Do not edit.\n#pragma once\n#define DOCKPIPE_RELEASE_VERSION \"${version}\"\n")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT_FILE}" "${content}")
