// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

type PipeLangArithmeticError string

const (
	PipeLangArithmeticOverflow       PipeLangArithmeticError = "overflow"
	PipeLangArithmeticDivisionByZero PipeLangArithmeticError = "division_by_zero"
)

type PipeLangArithmeticResult[T any] struct {
	OK    bool
	Value T
	Error PipeLangArithmeticError
}

func pipelangCheckedAddInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if (right > 0 && left > maximum-right) || (right < 0 && left < minimum-right) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: left + right}
}

func pipelangCheckedSubtractInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if (right < 0 && left > maximum+right) || (right > 0 && left < minimum+right) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: left - right}
}

func pipelangCheckedMultiplyInt64(left, right int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if left == 0 || right == 0 {
		return PipeLangArithmeticResult[int64]{OK: true}
	}
	if (left == minimum && right == -1) || (right == minimum && left == -1) {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	value := left * right
	if value/right != left {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: value}
}

func pipelangCheckedNegateInt64(value int64) PipeLangArithmeticResult[int64] {
	const maximum = int64(9223372036854775807)
	const minimum = -maximum - 1
	if value == minimum {
		return PipeLangArithmeticResult[int64]{Error: PipeLangArithmeticOverflow}
	}
	return PipeLangArithmeticResult[int64]{OK: true, Value: -value}
}

func pipelangCheckedDivideBinary64(left, right float64) PipeLangArithmeticResult[float64] {
	if right == 0 {
		return PipeLangArithmeticResult[float64]{Error: PipeLangArithmeticDivisionByZero}
	}
	return PipeLangArithmeticResult[float64]{OK: true, Value: left / right}
}

func PipeLangNegate(p0 int64) PipeLangArithmeticResult[int64] {
	return pipelangCheckedNegateInt64(p0)
}
