// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

import "unicode/utf8"

func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

type PipeLangOptional[T any] interface {
	pipelangOptional(T)
}

type pipelangOptionalSome[T any] struct {
	value T
}

func (pipelangOptionalSome[T]) pipelangOptional(T) {}

type pipelangOptionalNone[T any] struct{}

func (pipelangOptionalNone[T]) pipelangOptional(T) {}

func pipelangValidateOptionalPayload[T any](value T) {
	switch typed := any(value).(type) {
	case string:
		pipelangValidateText(typed)
	case int64, float64, bool:
		_ = typed
	case PipeLangRecordTestPackageAppRootContainerrow:
		pipelangValidateRecordTestPackageAppRootContainerrow(typed)
	default:
		panic("invalid PipeLang Optional payload")
	}
}

func pipelangSomeValue[T any](value T) PipeLangOptional[T] {
	result := PipeLangOptional[T](pipelangOptionalSome[T]{value: value})
	pipelangValidateOptional(result)
	return result
}

func pipelangNoneValue[T any]() PipeLangOptional[T] {
	return pipelangOptionalNone[T]{}
}

func pipelangValidateOptional[T any](value PipeLangOptional[T]) {
	switch typed := value.(type) {
	case pipelangOptionalSome[T]:
		pipelangValidateOptionalPayload(typed.value)
	case pipelangOptionalNone[T]:
	default:
		panic("invalid PipeLang Optional value")
	}
}

func pipelangHasValue[T any](value PipeLangOptional[T]) bool {
	pipelangValidateOptional(value)
	_, present := value.(pipelangOptionalSome[T])
	return present
}

func pipelangValueOr[T any](value PipeLangOptional[T], fallback T) T {
	pipelangValidateOptional(value)
	pipelangValidateOptionalPayload(fallback)
	switch typed := value.(type) {
	case pipelangOptionalSome[T]:
		return typed.value
	case pipelangOptionalNone[T]:
		return fallback
	default:
		panic("invalid PipeLang Optional value")
	}
}

type PipeLangRecordTestPackageAppRootContainerrow struct {
	Id      string
	Name    string
	Running bool
}

func pipelangValidateRecordTestPackageAppRootContainerrow(value PipeLangRecordTestPackageAppRootContainerrow) {
	pipelangValidateText(value.Id)
	pipelangValidateText(value.Name)
}

func PipeLangAbsentRow() PipeLangOptional[PipeLangRecordTestPackageAppRootContainerrow] {
	return pipelangNoneValue[PipeLangRecordTestPackageAppRootContainerrow]()
}

func PipeLangForwardRow(p0 PipeLangOptional[PipeLangRecordTestPackageAppRootContainerrow]) PipeLangOptional[PipeLangRecordTestPackageAppRootContainerrow] {
	pipelangValidateOptional(p0)
	return p0
}

func PipeLangHasRow(p0 PipeLangOptional[PipeLangRecordTestPackageAppRootContainerrow]) bool {
	pipelangValidateOptional(p0)
	return pipelangHasValue(p0)
}

func PipeLangPresentRow(p0 PipeLangRecordTestPackageAppRootContainerrow) PipeLangOptional[PipeLangRecordTestPackageAppRootContainerrow] {
	pipelangValidateRecordTestPackageAppRootContainerrow(p0)
	return pipelangSomeValue(p0)
}

func PipeLangRowOr(p0 PipeLangOptional[PipeLangRecordTestPackageAppRootContainerrow], p1 PipeLangRecordTestPackageAppRootContainerrow) PipeLangRecordTestPackageAppRootContainerrow {
	pipelangValidateOptional(p0)
	pipelangValidateRecordTestPackageAppRootContainerrow(p1)
	return pipelangValueOr(p0, p1)
}
