// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

import "unicode/utf8"

func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

type PipeLangOptional[T any] interface {
	pipelangOptional(T)
}

type pipelangOptionalSome[T any] struct {
	value T
}

func (pipelangOptionalSome[T]) pipelangOptional(T) {}

type pipelangOptionalNone[T any] struct{}

func (pipelangOptionalNone[T]) pipelangOptional(T) {}

func pipelangSomeValue[T any](value T) PipeLangOptional[T] {
	result := PipeLangOptional[T](pipelangOptionalSome[T]{value: value})
	pipelangValidateOptional(result)
	return result
}

func pipelangNoneValue[T any]() PipeLangOptional[T] {
	return pipelangOptionalNone[T]{}
}

func pipelangValidateOptional[T any](value PipeLangOptional[T]) {
	switch typed := value.(type) {
	case pipelangOptionalSome[T]:
		if text, ok := any(typed.value).(string); ok {
			pipelangValidateText(text)
		}
	case pipelangOptionalNone[T]:
	default:
		panic("invalid PipeLang Optional value")
	}
}

func pipelangHasValue[T any](value PipeLangOptional[T]) bool {
	pipelangValidateOptional(value)
	_, present := value.(pipelangOptionalSome[T])
	return present
}

func PipeLangAbsent() PipeLangOptional[string] {
	return pipelangNoneValue[string]()
}

func PipeLangForward(p0 PipeLangOptional[string]) PipeLangOptional[string] {
	pipelangValidateOptional(p0)
	return p0
}

func PipeLangHasValue(p0 PipeLangOptional[string]) bool {
	pipelangValidateOptional(p0)
	return pipelangHasValue(p0)
}

func PipeLangPresent(p0 string) PipeLangOptional[string] {
	return pipelangSomeValue(p0)
}
