// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

import "unicode/utf8"

func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

type PipeLangRecordTestPackageAppRootContainerrow struct {
	Id      string
	Name    string
	Running bool
}

func pipelangValidateRecordTestPackageAppRootContainerrow(value PipeLangRecordTestPackageAppRootContainerrow) {
	pipelangValidateText(value.Id)
	pipelangValidateText(value.Name)
}

func pipelangValidateListTestPackageAppRootContainerrow(values []PipeLangRecordTestPackageAppRootContainerrow) {
	if values == nil {
		panic("invalid PipeLang List value")
	}
	for _, value := range values {
		pipelangValidateRecordTestPackageAppRootContainerrow(value)
	}
}

func pipelangCloneListTestPackageAppRootContainerrow(values []PipeLangRecordTestPackageAppRootContainerrow) []PipeLangRecordTestPackageAppRootContainerrow {
	pipelangValidateListTestPackageAppRootContainerrow(values)
	result := make([]PipeLangRecordTestPackageAppRootContainerrow, len(values))
	copy(result, values)
	return result
}

func pipelangEmptyListTestPackageAppRootContainerrow() []PipeLangRecordTestPackageAppRootContainerrow {
	return make([]PipeLangRecordTestPackageAppRootContainerrow, 0)
}

func pipelangSingletonListTestPackageAppRootContainerrow(value PipeLangRecordTestPackageAppRootContainerrow) []PipeLangRecordTestPackageAppRootContainerrow {
	pipelangValidateRecordTestPackageAppRootContainerrow(value)
	return []PipeLangRecordTestPackageAppRootContainerrow{value}
}

func pipelangFilterByTextListTestPackageAppRootContainerrowField1(values []PipeLangRecordTestPackageAppRootContainerrow, key string) []PipeLangRecordTestPackageAppRootContainerrow {
	pipelangValidateListTestPackageAppRootContainerrow(values)
	pipelangValidateText(key)
	result := make([]PipeLangRecordTestPackageAppRootContainerrow, 0, len(values))
	for _, value := range values {
		if pipelangCompareOrdinalText(value.Name, key) == 0 {
			result = append(result, value)
		}
	}
	return result
}

func PipeLangFilterRows(p0 []PipeLangRecordTestPackageAppRootContainerrow, p1 string) []PipeLangRecordTestPackageAppRootContainerrow {
	pipelangValidateListTestPackageAppRootContainerrow(p0)
	return pipelangFilterByTextListTestPackageAppRootContainerrowField1(p0, p1)
}
