// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

import "unicode/utf8"

func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

type PipeLangRecordTestPackageAppRootRow struct {
	Id    string
	Count int64
	Ratio float64
	Ready bool
}

func pipelangValidateRecordTestPackageAppRootRow(value PipeLangRecordTestPackageAppRootRow) {
	pipelangValidateText(value.Id)
}

func pipelangNewRecordTestPackageAppRootRow(field0 string, field1 int64, field2 float64, field3 bool) PipeLangRecordTestPackageAppRootRow {
	value := PipeLangRecordTestPackageAppRootRow{
		Id:    field0,
		Count: field1,
		Ratio: field2,
		Ready: field3,
	}
	pipelangValidateRecordTestPackageAppRootRow(value)
	return value
}

func PipeLangCreate(p0 string, p1 int64, p2 float64, p3 bool) PipeLangRecordTestPackageAppRootRow {
	return pipelangNewRecordTestPackageAppRootRow(p0, p1, p2, p3)
}
