// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

import "unicode/utf8"

func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

type PipeLangRecordTestPackageAppRootRow struct {
	Id    string
	Count int64
	Ratio float64
	Ready bool
}

func pipelangValidateRecordTestPackageAppRootRow(value PipeLangRecordTestPackageAppRootRow) {
	pipelangValidateText(value.Id)
}

func PipeLangSame(p0 PipeLangRecordTestPackageAppRootRow, p1 PipeLangRecordTestPackageAppRootRow) bool {
	pipelangValidateRecordTestPackageAppRootRow(p0)
	pipelangValidateRecordTestPackageAppRootRow(p1)
	return (p0 == p1)
}
