// Code generated by PipeLang pipelang.compiler.v1; DO NOT EDIT.
package pipelanggenerated

import "unicode/utf8"

func pipelangValidateText(value string) {
	if !utf8.ValidString(value) {
		panic("invalid PipeLang string: value is not valid UTF-8")
	}
}

func pipelangConcatText(left, right string) string {
	pipelangValidateText(left)
	pipelangValidateText(right)
	return left + right
}

func pipelangCompareOrdinalText(left, right string) int {
	pipelangValidateText(left)
	pipelangValidateText(right)
	for len(left) > 0 && len(right) > 0 {
		leftScalar, leftWidth := utf8.DecodeRuneInString(left)
		rightScalar, rightWidth := utf8.DecodeRuneInString(right)
		if leftScalar < rightScalar {
			return -1
		}
		if leftScalar > rightScalar {
			return 1
		}
		left = left[leftWidth:]
		right = right[rightWidth:]
	}
	if len(left) < len(right) {
		return -1
	}
	if len(left) > len(right) {
		return 1
	}
	return 0
}

func pipelangIsTextWhitespace17(scalar rune) bool {
	switch {
	case scalar >= 0x9 && scalar <= 0xD:
		return true
	case scalar == 0x20:
		return true
	case scalar == 0x85:
		return true
	case scalar == 0xA0:
		return true
	case scalar == 0x1680:
		return true
	case scalar >= 0x2000 && scalar <= 0x200A:
		return true
	case scalar >= 0x2028 && scalar <= 0x2029:
		return true
	case scalar == 0x202F:
		return true
	case scalar == 0x205F:
		return true
	case scalar == 0x3000:
		return true
	}
	return false
}

func pipelangTrimText(value string) string {
	pipelangValidateText(value)
	start := 0
	for start < len(value) {
		scalar, size := utf8.DecodeRuneInString(value[start:])
		if !pipelangIsTextWhitespace17(scalar) {
			break
		}
		start += size
	}
	end := len(value)
	for end > start {
		scalar, size := utf8.DecodeLastRuneInString(value[:end])
		if !pipelangIsTextWhitespace17(scalar) {
			break
		}
		end -= size
	}
	return value[start:end]
}

func PipeLangTrim(p0 string) string {
	return pipelangTrimText(p0)
}
