file(MAKE_DIRECTORY "${TEST_OUTPUT}/without-git")
set(OUTPUT_FILE "${TEST_OUTPUT}/BuildVersion.h")
set(SOURCE_DIR "${TEST_OUTPUT}/without-git")
set(CMAKE_DISABLE_FIND_PACKAGE_Git TRUE)
set(RELEASE_VERSION "")
include("${VERSION_SCRIPT}")
file(READ "${OUTPUT_FILE}" generated)
if(NOT generated MATCHES "dev[+]unknown")
    message(FATAL_ERROR "Build without Git must remain explicitly developmental")
endif()

foreach(release IN ITEMS "0.6.12" "0.6.12-staging.123.1.0123456789ab")
    set(RELEASE_VERSION "${release}")
    include("${VERSION_SCRIPT}")
    file(READ "${OUTPUT_FILE}" generated)
    string(FIND "${generated}" "\"${release}\"" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Explicit release version was not preserved: ${release}")
    endif()
endforeach()

# Reusing the build directory must not retain the previous explicit release.
set(RELEASE_VERSION "")
include("${VERSION_SCRIPT}")
file(READ "${OUTPUT_FILE}" generated)
if(NOT generated MATCHES "dev[+]unknown")
    message(FATAL_ERROR "Incremental generation retained a stale release version")
endif()
