#!/usr/bin/env python3
"""Render exact authored embed inputs; never infer bundle membership from a directory."""
import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
ROOTS = ('src/core/', 'workflows/', 'packages/')
RELEASE = tuple('packages/dorkpipe/resolvers/dorkpipe/assets/tooling/bin/linux/' + name
                for name in ('dockpipe', 'dorkpipe', 'mcpd'))


def authored(root):
    paths = subprocess.check_output(['git', 'ls-files', '--cached', '--others', '--exclude-standard', '-z'], cwd=root).decode().split('\0')
    deleted = set(subprocess.check_output(['git', 'ls-files', '--deleted', '-z'], cwd=root).decode().split('\0'))
    # Match the former Go directory walk: dot/underscore entries were omitted.
    selected = sorted(p for p in set(paths) - deleted if (p in ('VERSION', 'assets/entrypoint.sh') or p.startswith(ROOTS))
                      and not any(part.startswith(('.', '_')) for part in p.split('/'))
                      and not any((parent / 'go.mod').is_file() for parent in (root / p).parents if parent != root and parent.is_relative_to(root)))
    for name in selected:
        path = root / name
        if any(c in name for c in '*?[') or not path.is_file() or any(p.is_symlink() for p in [path, *path.parents]):
            raise ValueError('non-regular authored input: ' + name)
    return selected


def render(paths, variable):
    return ('// Code generated by release/packaging/embedded-inputs.py; DO NOT EDIT.\n'
            'package dockpipe\n\nimport "embed"\n\n' +
            ''.join('//go:embed ' + json.dumps(p) + '\n' for p in paths) +
            'var ' + variable + ' embed.FS\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--release', action='store_true')
    args = parser.parse_args()
    if args.release:
        for name in RELEASE:
            path = ROOT / name
            if not path.is_file() or any(p.is_symlink() for p in [path, *path.parents]) or not path.stat().st_size:
                parser.error('missing regular release input: ' + name)
        path = ROOT / 'embed_release_generated.go'
        content = render(RELEASE, 'preparedReleaseFS') + '\nfunc init() { releaseFS = preparedReleaseFS }\n'
        if path.exists() and path.read_text() != content:
            parser.error('refusing to overwrite a different release embed declaration')
    else:
        path = ROOT / 'embed_assets.go'
        content = render(authored(ROOT), 'authoredFS')
    if args.check:
        if not path.exists() or path.read_text() != content:
            parser.error('embedded file manifest is stale; regenerate and review it')
    else:
        path.write_text(content)


if __name__ == '__main__':
    main()
